### ISSUE TITLE
Not able to create an account with an email with hey.com as host address

### ISSUE THREAD

**Issue by anubhav8421** [chatwoot/chatwoot#1033]
**Describe the bug**
I was creating an account on https://app.chatwoot.com/app/auth/signup
Used <my-name>@hey.com as the email address
Negative Validation occurred

**To Reproduce**
1. Go to https://app.chatwoot.com/app/auth/signup
2. In the email field add, type any email with host as hey.com address
3. Click on the enter password field
4. See error 'Email Invalid'

**Expected behavior**
hey.com as a host should be accepted 

**Screenshots**
![image](https://user-images.githubusercontent.com/18699797/87302706-8690e900-c52f-11ea-80e9-875df3c2fec1.png)

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser firefox
 - Version 78.0.1

**Comment by sojan-official** [comment]
@anubhav8421  the way current flow works is for creating the account you just need an `account name` and `email` . The password is set on the confirmation step 

![Screenshot 2020-07-13 at 7 10 15 PM](https://user-images.githubusercontent.com/73185/87311321-b8f51300-c53c-11ea-83e0-5814b7c62f13.png)

there isn't a specific error for @hey.com . But we will reevaluate the UX here since you find it confusing. let us know if you face further issues on signup.

**Comment by anubhav8421** [comment]
🤦🏻‍♂️ This was instinctive. I didn't read the label. Just entered email in the first field and entered the password in the second field.
