### ISSUE TITLE
Filter chain halted as :authenticate_user! rendered or redirected

### ISSUE THREAD

**Issue by CL545740896** [chatwoot/chatwoot#1057]
**Describe the bug**
1. POST "/api/v1/accounts/{account_id}/conversations/{conversation_id}/messages"
2. Can't verify CSRF token authenticity.
3. Filter chain halted as :authenticate_user! rendered or redirected 
4. Completed 401 Unauthorized
5. return {
    "errors": [
        "You need to sign in or sign up before continuing."
    ]
}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CL545740896** [comment]
Mybe  The Crsf  Problem , So  , I think  it just check the api_acess_token  is enough ! , It doesn't use Crsf

**Comment by sojan-official** [comment]
based on the investigation, it turned out the reason was Nginx skipping the `api_access_token` header.  

# Missing (disappearing) HTTP Headers¶

If you do not explicitly set underscores_in_headers on;, NGINX will silently drop HTTP headers with underscores (which are perfectly valid according to the HTTP standard). This is done in order to prevent ambiguities when mapping headers to CGI variables as both dashes and underscores are mapped to underscores during that process. . 

lets update the default Nginx config with this change

**Comment by pucilpet** [comment]
Should probably add underscores_in_headers on; to other deployments as well (I had the same issue on Caprover).

**Comment by sojan-official** [comment]
@pranavrajs  we could probably move towards. `api-acess-token` and keep the underscore version as a fallback. 
and update the documentation for the same.

**Comment by pranavrajs** [comment]
@sojan-official Sure, created an issue here https://github.com/chatwoot/chatwoot/issues/1615
