### ISSUE TITLE
Copy for self-assignment

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1077]
Change the copy from "Assigned to Pranav to Pranav" to "Pranav self-assigned this ticket."

<img width="333" alt="Screenshot 2020-07-21 10 59 40" src="https://user-images.githubusercontent.com/2246121/88016687-974dea00-cb41-11ea-8da4-183e2f4fdec4.png">

@sojan-official Thoughts?

**Comment by iammattmartin** [comment]
or maybe "Name took ownership" or "Name claimed conversation"

Are they called tickets or conversations? Keeping consistency with working in the UI might be better.

**Comment by sojan-official** [comment]
@pranavrajs We can stick with `conversation` since everything in the product is modeled under that name. so my suggestion is. `Pranav self-assigned this conversation` or `Assigned to self by Pranav`

@iammattmartin  using an alternative wording, we will also have to change the text for the case `assigned to user a by user b` . Also the action text of the dropdown is `Assign`, so I would be in favor of sticking with the naming.

**Comment by monarch0111** [comment]
@pranavrajs Is this still under consideration? If yes, I would like to work on this. Seems to be very small enhancement.

**Comment by pranavrajs** [comment]
@monarch0111 Please feel free to take. Please use the copy "{agent_name} self-assigned this conversation"
