### ISSUE TITLE
Enhancement: Limit email continuity to web-widget and email channels

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#1118]
> Is it possible to limit the new messages notification email that gets send to the user, to be only triggered if the channel is a widget channel? (Why's that? well, currently until the CRM features are better enhanced, we use the available fields to assign metadata manually via the DB, so for a channel like WhatsApp for example, we use the email field to add the email address if the contact is a current customer with us, but shortly stopped doing that since we noticed this would trigger the sending of email notifications to the user when new messages are added to the conversation by agents).

implement conditions before sending the email
- whether the last message was through email 
- check whether the message is from web widget and its a case of conversation continuity ( ie user gave email and went offline ) 

for future: Indication on the UI whether the message will be sent to the widget or to email

**Comment by WevrLabs** [comment]
Thanks for the prompt response in adding this to the To-Do!

------------
I want to add a note on this point here, 
> ( ie user gave email and went offline )

Maybe the condition for triggering the email could be the "read" status, rather than the "online/offline" status? This is because in some cases a user would have the window open but not focused or minimized, etc, and if there were new messages added, they may get missed if the user closes the window without checking further for new updates, so in this case, the email notification can get triggered after a certain amount of time when there's no "read" status received (ideally I guess 10 minutes window is fine).
