### ISSUE TITLE
Full Name vs Display Name

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1136]
**Describe the bug**
In the widget/email from 1.7.0, the name set in the "Display Name" is not used or is inconsistent. Instead the "Full Name" continues to be used as noted case #972.

**Expected behaviour**
Given the title of "Display Name", we'd expect to see that in the widget and used in emails and the full name used to staff/admin.

It seems that both the Display Name and Full Name are mixed...
Display Name shows in the admin area and Full Name shows in the widget but in the email, Display Name is used.

There does not appear to be any consistency in which is used and where.

**Comment by pranavrajs** [comment]
@iammattmartin Sorry I missed the previous comment on this. 

This is the current behaviour. 

1. Display Name: It will be used everywhere except agent listing for admin
2. Full Name: It will be used only in the agent listing for admin

Upcoming release: We will provide a config for the admin to set what name type should be used in Dashboard and widget.

Is the current behaviour mentioned above consistent with what you are seeing now or does it have further issues? 

Note: If you have not set `display_name` for the user `full_name` will be used by default.

**Comment by iammattmartin** [comment]
Still a bug as far as I can see.

I set each option to different values.

Display: Name 1
Full: Name 2

In the Widget, I got "Name 2" based on the Full Name setting but in the email, I got "Name 1" for the Display Name.

So it appears that the email is correct and using the display name but the widget is still using the full name incorrectly.

**Comment by iammattmartin** [comment]
This was mostly resolved due to an issue with the updater not clearing the cached objects.

Although I can see that the name under the "Collaborators" tab in the UI uses the Display Name and not the Full Name as well as the current logged in staff name (bottom left).

I'd probably expect that, given the conditions you mention, it should be using the Full Name..?

I think the simple rule of, if in an admin/staff area, the full name should always be used and on the widget, the display should always be used if set.

**Comment by pranavrajs** [comment]
> I think the simple rule of, if in an admin/staff area, the full name should always be used and on the widget, the display should always be used if set. 

This makes sense we will check this out.

**Comment by pranavrajs** [comment]
Also on that note, we would want to keep message area using Display Name instead of Full Name. I've mentioned below the places where it would be ideal to use Display Name instead of long full Name

1. Message sent by indicator

<img width="298" alt="Screenshot 2020-08-11 at 11 30 00 PM" src="https://user-images.githubusercontent.com/2246121/89931979-94b74f80-dc2a-11ea-84db-aae3623d989f.png">

2. Assign agent

<img width="506" alt="Screenshot 2020-08-11 at 11 31 07 PM" src="https://user-images.githubusercontent.com/2246121/89932104-bd3f4980-dc2a-11ea-98f9-31eb797def23.png">

3. Sidebar Profile
<img width="236" alt="Screenshot 2020-08-11 at 11 31 18 PM" src="https://user-images.githubusercontent.com/2246121/89932126-c4665780-dc2a-11ea-9720-95663607ec47.png">

4. Activity messages.
<img width="448" alt="Screenshot 2020-08-11 at 11 31 53 PM" src="https://user-images.githubusercontent.com/2246121/89932175-d8aa5480-dc2a-11ea-869a-cfa2ded1c04f.png">

@iammattmartin Do you have a compelling case to use Full name in these places.

**Comment by iammattmartin** [comment]
I think everywhere that is only viewable to staff, should always be the full name of the agent.

At least for us, we'll be using the staff's first name on the display option, so if you have multiple people with the same name, that will get confusing on the admin side.

(Additionally, we may look to add the job title on the full name: i.e "First Last (Job)", for dealing with staff across teams.

I can't think of any logical reason why only the display name would be suitable when you have more than a handful of staff. If you only have one or two, that would be fine but I expect most using this will have more than that.

**Comment by pranavrajs** [comment]
@iammattmartin Make sense, I believe a toggle both FullName vs Display Name is best here.

**Comment by iammattmartin** [comment]
Is there any chance of pushing this out in a release soon @pranavrajs. Wire more using it, having the abbreviated name internally is causing some degree of confusion.

**Comment by pranavrajs** [comment]
@iammattmartin We don't have much feedback on this one from our users. So instead of spending more time on this to see whether a toggle is required or not, I would just use `Display Name` for the widget & emails and use `Full Name` in the dashboard.
