### ISSUE TITLE
"Add label" dialog does not show buttons to Create/Cancel

### ISSUE THREAD

**Issue by Giszmo** [chatwoot/chatwoot#1228]
**Describe the bug**

When I open the color picker in the "Add label" dialog, the buttons scroll off-dialog and I cannot scroll them back in.

**Screenshots**

![Screenshot from 2020-09-12 19-23-00](https://user-images.githubusercontent.com/96378/93006051-ec005680-f52d-11ea-9995-b2292efe3e47.png)

**Environment**

Server: CapRover on Digitalocean, running whatever the process gave me when installing it yesterday. In CapRover I can't find any version information and in the ChatWoot frontend neither.

Client: Ubuntu 20.04, Firefox 80.0.1 (64-bit)

**Comment by chethanagopinath** [comment]
Hi @pranavrajs, I was looking for issues to work on for Hacktoberfest and I would love to pick this up if possible. Thanks!

**Comment by pranavrajs** [comment]
@chethanagopinath Sure, feel free to take it. It is an issue with event propagation. vue-clickaway events are not captured if the component is loaded inside the modal.

**Comment by chethanagopinath** [comment]
@pranavrajs Awesome, I will check it out. Could you assign me to it as I am unable to do it :/

**Comment by chethanagopinath** [comment]
@sojan-official Hi, I was actually working on this. Not sure why I was unassigned :(

**Comment by chethanagopinath** [comment]
@sojan-official Hi, I was actually working on this. Not sure why I was unassigned :( I know that it's been a long time since I commented, but I was stuck with some stuff, so if possible, I would like to work on this and finish it.

**Comment by sojan-official** [comment]
@chethanagopinath  sorry about that. I think I misread the previous comment  😅 . I have reassigned it to you.

**Comment by chethanagopinath** [comment]
@sojan-official Haha, I checked it now and I understand why you would think that. :) Thanks again.

**Comment by chethanagopinath** [comment]
@pranavrajs Thank you so much for your patience and my apologies for being so late. I hope I can still work on the issue. I also had a couple of follow up questions on it -
1) On the `Add label` modal, when I click on the color picker, choose a color, and click anywhere within the `Add Label` modal, but NOT on the color picker, the color picker should disappear and I will be shown the modal. I made this assumption as you spoke about `vue-clickaway`.
2) Should the `Create` button and `Show label on sidebar` checkbox be visible on clicking on the color picker and on scroll? 
3) Should both the above 2 points be implemented instead of either 1 or 2?
Again, my apologies for the delay.

**Comment by nithindavid** [comment]
Closing in favour of #2636
