### ISSUE TITLE
Agent avatar is disappearing

### ISSUE THREAD

**Issue by Giszmo** [chatwoot/chatwoot#1258]
**Describe the bug**

After setting the avatar in the agent's profile it is shown bottom left for example. Refreshing the site also preserves the avatar. At a later point though (next day?) the avatar is unset or disappeared.

**To Reproduce**

???

**Environment**

CapRover ChatWoot v1.7.2

**Additional context**

This happened twice now and once before potentially corrupting the database with the DOS vulnerability described to the team in private.

**Comment by pranavrajs** [comment]
@Giszmo Have you configured any Cloud storage? Otherwise, the attachments will be removed from Caprover temp storage on restart https://www.chatwoot.com/docs/configuring-cloud-storage

**Comment by Giszmo** [comment]
I installed using caprover but did not configure "cloud storage".

That said, if the standard installation is by default losing data, that is a bug. If the disk runs full, that is expected. If the performance is not optimal, that might be a short-coming of not using "cloud storage" but I have 72GB free on the server and no performance issues, so losing data is perceived as bug.

**Comment by pranavrajs** [comment]
@Giszmo This is already discussed in #1166. This is not the problem with Chatwoot, it is the way docker deployments, in general, is working. We need to define a volume for locally uploaded storage items, otherwise, Caprover restarts would clear the locally uploaded files. We have not yet investigated how supporting a local volume would affect the deployment if it is using more than one servers. That is the reason why we are suggesting one of the cloud storages until then. 

Closing it here as #1166 has more context and this is a duplicate ticket for the same.
