### ISSUE TITLE
feat: Profanity filter in conversation

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1280]
- Allow admin to configure a profanity filter for messages
- Allow admin to configure the words used in the filter.
- Replace all matching content in the message with **** 
- Apply the filter for both agent and user.

#### A sample message would look like the one below

<img width="193" alt="Screenshot 2020-09-27 at 6 56 48 PM" src="https://user-images.githubusercontent.com/2246121/94366076-34557200-00f3-11eb-83d2-13e181f44813.png">

**Comment by akashdotsrivastava** [comment]
@pranavrajs This looks like something I can work on. Is it okay if I take this?

**Comment by pranavrajs** [comment]
@akashdotsrivastava Feel free to take it :)

**Comment by akashdotsrivastava** [comment]
@pranavrajs Just a few questions/confirmations before I get into actual code

1. Where does this setting/s live? Inbox level or account level? Asking because [This discussion](https://github.com/chatwoot/chatwoot/issues/418#issuecomment-703093522) suggests new settings on the account level.

2. Does it have to be just words, or phrases too that should be allowed and masked as individual profanities. For eg. `b****` is objectionable , but `son of a b****` is too. 😊 I know phrases will come with more complexity (varying spaces between words etc), and may produce false positives too. So just a confirmation, are we sticking to just words for now? Or we want to put in efforts for phrases too at this time?

**Comment by sojan-official** [comment]
Closing this for now based on the technical discussions.  With #1353 ( ability to delete message ) should suffice meanwhile.
