### ISSUE TITLE
feat: SSO via External Authentication, Oauth integration

### ISSUE THREAD

**Issue by vfasoulas** [chatwoot/chatwoot#1318]
**Is your feature request related to a problem? Please describe.**
No, It's an Enhancement 

**Describe the solution you'd like**
With this feature will be possible to login as an agent my google, microsoft, or facebook account.
I suggest, a general oauth implementation for example with environment variables, to be possible to login with any oauth server for example company oauth services.

**Describe alternatives you've considered**

**Additional context**

**Comment by sbauch** [comment]
Is the chatwoot team interested in PRs that add this functionality?

I'm a maintainer of [Osso](https://github.com/enterprise-oss/osso), a ruby service that enables SAML-based SSO via OAuth from an app like chatwoot. We're considering using chatwoot in our stack, and would prefer to be able to login using SSO, so we could implement OAuth support in chatwoot generally in order to support our SAML => OAuth provider in our instance.

**Comment by pranavrajs** [comment]
@sbauch Thanks for introducing Osso, let us take a look at the library, will revert to you if it is suitable for our pipeline.

cc: @sojan-official

**Comment by ipadmini22** [comment]
Are there updates to adding SSO to chatwoot?

**Comment by sojan-official** [comment]
> Are there updates to adding SSO to chatwoot?

Ability to use External sso auth providers are still in our backlog

But you can leverage platform APIs to implement a custom SSO : 
https://github.com/chatwoot/chatwoot/wiki/Building-on-Top-of-Chatwoot:-Platform-APIs
https://www.chatwoot.com/developers/api/#operation/get-sso-url-of-a-user

**Comment by voko3456** [comment]
hi @sojan-official when I get SSO login URL its always redirect to /dashboard can I redirect to /settings/inboxes/new or /mentions/conversations

**Comment by pranavrajs** [comment]
Tracking it via #5420
