### ISSUE TITLE
Send emails when agent reply to the conversation in dashboard

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#139]

**Comment by sony-mathew** [comment]
I'm taking this up and working on this.

**Comment by sony-mathew** [comment]
As the conversations are in the format of chat messages, the agent/customer tends to send short messages in a frequent interval rather than one long message. Considering this fact, when there is a new message activity on a conversation, we will be sending an email after a few minutes from the point when the first message was sent. This email content will have a couple of previous messages and all the new messages.
