### ISSUE TITLE
Load testing using Locust on Self hosted Chatwoot

### ISSUE THREAD

**Issue by bsbarkur** [chatwoot/chatwoot#1406]
**Describe the bug**

DB started throwing errors when doing load testing using locust for 500 users at spawn rate of 6 users sec. Could you please tell us what is the purpose of the display_id and index below and why concurrent inserts to db are failing at higher loads ?

**Server logs**

The DB logs were showing this:

2020-11-13 04:41:07.991 UTC [4251] ERROR:  duplicate key value violates unique constraint "index_conversations_on_account_id_and_display_id"

2020-11-13 04:41:07.991 UTC [4251] DETAIL:  Key (account_id, display_id)=(4, 2548) already exists.
  | 2020-11-13 04:41:07.991 UTC [4251] STATEMENT:  INSERT INTO "conversations" ("account_id", "inbox_id", "created_at", "updated_at", "contact_id", "display_id", "contact_inbox_id") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"

2020-11-13 04:41:07.991 UTC [4253] ERROR:  duplicate key value violates unique constraint "index_conversations_on_account_id_and_display_id"
  | 2020-11-13 04:41:07.991 UTC [4253] DETAIL:  Key (account_id, display_id)=(4, 2548) already exists.
  | 2020-11-13 04:41:07.991 UTC [4253] STATEMENT:  INSERT INTO "conversations" ("account_id", "inbox_id", "created_at", "updated_at", "contact_id", "display_id", "contact_inbox_id") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"

 2020-11-13 04:41:08.329 UTC [4252] ERROR:  duplicate key value violates unique constraint "index_conversations_on_account_id_and_display_id"
 2020-11-13 04:41:08.329 UTC [4252] DETAIL:  Key (account_id, display_id)=(4, 2550) already exists.

**Environment**

The above chatwoot setup was on self hosted openshift servers using docker strategy.

**Additional context**

Help us to diagnose the issue we have indicated above. Also, please point us to any load testing use-cases and real life scenario studies on chatwoot in large scale deployments. It will be useful. Also statistics on the requests chatwoot can handle in production deployments will be useful and helpful.

**Comment by pranavrajs** [comment]
@bsbarkur Can you please describe the way you have tested the application? Is it tested on a single or a swarm of Docker? Did you try calling the API or have emulated the UI clicks using Locust?

display_id - This is the ticket number for a conversation in a particular account.

> Help us to diagnose the issue we have indicated above. Also, please point us to any load testing use-cases and real life scenario studies on chatwoot in large scale deployments. It will be useful. Also statistics on the requests chatwoot can handle in production deployments will be useful and helpful.

For a page with 1M views per month, a 4GB server should be good enough. Our production app handle close to 40rps now, haven't seen this issue so far.

Also, I'm not sure if 6 conversations per sec is a right metric to be tested, since we are building a support channel not a conversation infrastructure.

**Comment by sorumehta** [comment]
@pranavrajs I think due to concurrent new conversation requests in this case, the display_id assigned to more than one new conversations is same, which is causing the unique constraint error while writing to the conversations table. 
Is there a way to assign incremental display_ids to concurrent conversations requests?

**Comment by pranavrajs** [comment]
@sorumehta I understood that. 

> Is there a way to assign incremental display_ids to concurrent conversations requests?

`display_id` is kind of auto_increment field specific to the account. This logic might be executed at the model callbacks. I have not figured out a way to do it at the DB level. If that is possible, then this problem would resolved.

**Comment by sorumehta** [comment]
@pranavrajs 

>  I have not figured out a way to do it at the DB level. If that is possible, then this problem would be resolved.

I think creating a sequence object in the db and using nextval() might help? I am not sure. If it works for me I will create a pull request. 
Do let me know your thoughts on this.
Thanks.

**Comment by pranavrajs** [comment]
@sorumehta Feel free to raise request, we can test it out.
