### ISSUE TITLE
Contact Card/Grouping Improvements

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1459]
In the current release with the contacts list, there may need to be a consideration to contacts with only a mobile/cell number such as from WhatsApp.

These contacts are not grouped in one meaning that if you have multiple conversations from the same number, they appear as separate contacts.

This appears to happen if those conversations are via different inboxes, which is fine but this does not then follow the same grouping as with email which if the same email is used, they are all grouped and appear in the contacts "conversations".

In addition, being able to tell on a merged contact the inbox that a previous conversation was received on via the contacts card would be needed if all inboxes are being merged in such a way.

**Comment by pranavrajs** [comment]
@iammattmartin I guess this would be covered in #258

**Comment by pranavrajs** [comment]
Instead of just email address, merge via phone number would also make sense.

**Comment by iammattmartin** [comment]
I suspect so, yes 👍

**Comment by WevrLabs** [comment]
> Instead of just email address, merge via phone number would also make sense.

Speaking of merging, currently in a use case such as if a user contacted via widget (and then a contact is created based on sdk input), if this user comes back later from a different session (even if not logged in, and just provided the email) this conversation will be linked to the previously created contact. (I have some reservations with this behaviour concerning identity spoofing, but I employed a workaround to overcome this). Continuing with the topic, what I primarily wanted to highlight, is the ability to merge contacts from dashboard directly, because if the said user for instance reached out via another type of inbox (WhatsApp, twitter, etc) and I try to update this recently created contact with the user's data, the email field input won't be accepted due to the previously created contact. I think instead of preventing adding the info, maybe prompt for merger with previous contact (after all, this technically still happens behind the scenes in the case of establishing conversations from different sessions with the same email address).

**Comment by pranavrajs** [comment]
@iammattmartin @WevrLabs Closing this as the merge contact option is available via phone, email, and identifier. Please let me know if I missed anything here.
