### ISSUE TITLE
feat: Option to inject custom styles / css

### ISSUE THREAD

**Issue by vahid-neuralinc** [chatwoot/chatwoot#1598]
There should be an option to inject custom style or css so that users can customize look and feel of the chat widget as per their need.

For example:

I want to change 

[this, with shadows and rounded corners](https://drive.google.com/file/d/17vO30P6i2T_ZOYfzj77Gg1nRsL94zK90/view?usp=sharing)

to

[this, without shadows and rounded corners](https://drive.google.com/file/d/1JNbkMdZgvOQZ1KD-D97xAFJWy8q-mfnT/view?usp=sharing)

**Comment by mizbanpaytakht** [comment]
I tried to use customCSS like this but its not working:
`      (function(d,t) {
        var BASE_URL="";
        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=BASE_URL+"/packs/js/sdk.js";
        s.parentNode.insertBefore(g,s);
        g.onload=function(){
          window.chatwootSDK.run({
            websiteToken: '',
            baseUrl: BASE_URL,
            customCSS: 'p{direction: rtl;text-align: right;}'
          })
        }
      })(document,"script");`

nothing added into header !

> Actually, there is a 3rd option as well and it does not need a backend i.e. expose a variable "customCSS" to provide custom CSS in Javascript Widget code snippet e.g.:
> 
> ```
>     <script>
>       (function(d,t) {
>         var BASE_URL="https://app.chatwoot.com";
>         var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
>         g.src=BASE_URL+"/packs/js/sdk.js";
>         s.parentNode.insertBefore(g,s);
>         g.onload=function(){
>           window.chatwootSDK.run({
>             websiteToken: 'XXXXXXXX',
>             baseUrl: BASE_URL,
>             customCSS: '.myclass{blah: blah;}.myAnotherClass{blah: blah;}'
>           })
>         }
>       })(document,"script");
>     </script>
> ```
> 
> On widget rendering, this variable is injected into the head tag as <style> element.

**Comment by vaneetproton** [comment]
![Screenshot 2022-01-14 220722](https://user-images.githubusercontent.com/94404033/149551637-9996fb90-7130-4652-bd0a-1a1ee1da5d42.png)
Chatwoot widget is misaligned or something don't know but the white bubble should be in the center. I have a self-hosted chatwoot app. Installation done via Ubuntu script and no modification has been done. Can someone please advise?

**Comment by pranavrajs** [comment]
@vaneetproton Can you please share the URL to see what's going on?

**Comment by sojan-official** [comment]
We are still evaluating the best way to provide this functionality. Providing APIs to inject raw CSS into widgets could come with few caveats,

- It will significantly hinder the pace at which Chatwoot can ship new features in the widget since the team would have to be way too cautious about changing the HTML structure. 
- Chatwoot widget updates in future could break end-users CSS customizations.   

Also with the features for the widget like https://github.com/chatwoot/chatwoot/issues/2355 , https://github.com/chatwoot/chatwoot/issues/714 still pending, let's wait out for the widget design to stabilise before further exploring this. 

-------

Meanwhile, we are looking into making the widget more customizable with the following changes. 

- Flat Style: https://github.com/chatwoot/chatwoot/pull/4065 : as @vahid-neuralinc 's request chatwoot now support a flat style with the following configuration

```
window.chatwootSettings = {
  style: 'flat'
};
```

- Dark mode:  https://github.com/chatwoot/chatwoot/pull/4137
- Widget Builder : https://github.com/chatwoot/chatwoot/issues/4287

**Comment by prononext** [comment]
Are there any plans to inject custom CSS finally on the Live Chat Widget? That would be a dream. 

There are countless posts about customizing the live chat widget and instead of making it possible through GUI, with long development overhead, allowing users to inject their custom CSS would be the way to go. 

Please make it possible.

**Comment by steveninety** [comment]
> 

Agreed. I guess styling is not so important on a generic site. But when the styling doesn't (somewhat) match a branded site, it leaves a really messy impression.

**Comment by seanlau555** [comment]
When the customCSS can be used?

**Comment by pranavrajs** [comment]
Folks, we will not be supporting this. If a change is required, you can fork the repository and make the changes yourselves.
