### ISSUE TITLE
feat: Provide a one click copy option to key customer attributes

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#1607]
![image](https://user-images.githubusercontent.com/1277421/103670623-cd701080-4f9f-11eb-91ef-193b6951dc5c.png)

The email copy icon is always showing, show it only on hover

**Comment by iammattmartin** [comment]
It does always show but changes colour on mouse-over.

What is the issue exactly?

**Comment by WevrLabs** [comment]
> It does always show but changes colour on mouse-over.
> 
> What is the issue exactly? I think it is logical to have there so the user knows they can do this. Maybe the icon needs to change colour on mouse-over of the text too?

I agree

**Comment by nithindavid** [comment]
The idea was to add the same clipboard icon for phone number also. When two icons comes line by line, it might not look good.
On the other hand my assumption was if the user has the intention of copying the email/phone, they will definitely hover which will show the icon. So from that point user might learn about it.

@iammattmartin @WevrLabs @pranavrajs @sojan-official Let know if this sounds good? Else we will close the issue.

**Comment by iammattmartin** [comment]
I think the icon next to anything that you have the function on is good and with some colour change on mouseover so you know it does something.

In reality, it should be on any data layer that you may need to copy. Email, phone, twitter id etc.

**Comment by sojan-official** [comment]
@nithindavid  I think we can go with the idea of having the clipboard option becoming available for all data elements that required to be copied often. 

So customer attributes like email, phone, Twitter etc

But for doing this, I believe having the copy icon available on hover will a good direction in terms of UI/UX.

--- 

# copy icon visible by default 
- good for feature discoverability 
- with the option being available for multiple attributes stacked under.  it will affect the visual appeal and space negatively [ primary reasoning behind not proposing this interaction ]
- after a user discovers the feature, the icon visible by default doesn't add much value.

# copy icon visible on hover
- initial discoverability of the feature is reduced
- Hover is the interaction someone would go for when there is an intent to copy. 
   - Since this interaction makes the icon visible, The intention of use case will guide them to discover the feature.
- There isn't much difference in terms of effort required by both the styles of interactions.
