### ISSUE TITLE
Set default avatar image if profile image is not available

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#164]
- [ ] Create a component to display the first two letters of the name of the agent

**Comment by josemiguelo** [comment]
Can I take this one? I can do this!

**Comment by pranavrajs** [comment]
@josemiguelo Please feel free to take this. :)

**Comment by rojasTob** [comment]
Hi @pranavrajs  if there is another good first issue, I'm here ready to work.

**Comment by josemiguelo** [comment]
> @josemiguelo Please feel free to take this. :)

Just adding some tests to the implementation

**Comment by josemiguelo** [comment]
@pranavrajs I'm looking into these three cases:
1. When the src for the image is a valid string:
- and the URL is a valid one
- and the URL is a invalid one
2. When the src for the image is invalid (null or undefined)

For the two cases where image is not going to render, it is going to show the avatar. Is this the expected behaviour? Just to be on the same page..

**Comment by sojan-official** [comment]
@josemiguelo  that sounds good to me.  👍🏻

@rojasTob  do you have any preference, ie front end ( vue.js ) vs backend (rails ) ? I can find something for you to pick up.

**Comment by josemiguelo** [comment]
@rojasTob

**Comment by rojasTob** [comment]
> @josemiguelo that sounds good to me. 👍🏻
> 
> @rojasTob do you have any preference, ie front end ( vue.js ) vs backend (rails ) ? I can find something for you to pick up.

Hi @sojan-official, I would like to work on backend if is it possible.
