### ISSUE TITLE
feat: Ability to delete a contact

### ISSUE THREAD

**Issue by shrujan-kirusa** [chatwoot/chatwoot#1929]
**Is your enhancement request related to a problem? Please describe.**
During testing we have created multiple contacts with random e-mail Id's, But now we are unable to delete any of the contact. There is no API to delete a contact or on the web page also we don't see an option to delete a contact.

**Describe the solution you'd like**
It would be better if we can delete contact on webpage as well an API to delete a contact, there is already an API to create and edit contact so delete would also add more value to it.

**Describe alternatives you've considered**
If we were using self hosted option I guess we could delete on database directly but I didn't find any alternative way to delete a contact since we are using chatwoot on basic plan.

**Comment by iammattmartin** [comment]
It may also be better for GDPR/CCPA/etc that for contacts which have no conversations associated or any other data for them to be automatically deleted.

This means only data which is kept matching actual content (chat/message) data is kept.

**Comment by sojan-official** [comment]
## Acceptance 

## Backend
- API to delete contact conferring to the following standards 
```
DELETE api/v1/accounts/{account_id}/contacts/{id}
# returns head: ok  if successful 
# accessible only to administrators 
# agent tokens should return unauthorized
```
- triggering API should clear the following information
```
  -  Contact
  -  Conversations
  -  Contact Inboxes
  -  Associated Reporting Events
```
- Swagger documentation for the delete API 
-  Test and document the following implications hold when the same contact sends another message
   -  Website inbox: The current chat stops working if the user refreshes the page, a new contact gets generated, and they can continue the conversation on the widget 
      - Conversation continuity: fails because conversation doesn't exist
   - Facebook: New contact  / New conversation created 
   - Twitter: New contact / New conversations created 
   - SMS: New contact  / New conversations created 
   - Whatsapp: New contact  / New conversations created 
   - Email channel: New contact / New conversation created
   - API Channel: Further requests fail, need to create a new contact
- Webhook & Websocket events for contact deleted

## Frontend 
- Admins should be able to see the delete option in contact pannel in conversations view
<img width="470" alt="Screenshot 2021-08-22 at 10 48 54 PM" src="https://user-images.githubusercontent.com/73185/130364149-7d99c1fb-357e-4e22-b2eb-96db2546d5cb.png">

- Clicking on delete triggers a model and on confirm should delete the contact, all associated information
<img width="1173" alt="Screenshot 2021-08-22 at 11 03 45 PM" src="https://user-images.githubusercontent.com/73185/130364497-56a33028-ce6f-4de6-8f30-49da88f19187.png">



- Data associated to the contact should be cleared from the store if the contact delete event is received in websocket

```
  -  Contact
  -  Conversations
```

   
 ## Testing 
- Deleting the contact should clear the contact and all associated conversations 
- Deleting the contact should confirm the above behaviors documented for each channel
- Only Admin users should be able to delete a contact 
- Agents shouldn't be able to see the delete contact option
- Agents shouldn't be able to hit delete contact endpoint
- Reports should reflect correct data concerning the conversations that were deleted because of contact delete

**Comment by nithindavid** [comment]
The merge contact -> https://github.com/chatwoot/chatwoot/pull/2457 has context menu next to contact info which is a good place to keep the `delete contact` option.
