### ISSUE TITLE
Remove previous messages from email replies

### ISSUE THREAD

**Issue by ramezrafla** [chatwoot/chatwoot#2009]
**Is your enhancement request related to a problem? Please describe.**
When a customer (or an agent) replies to a message via email (conversation continuity), the entire email with its history is shown as a message in the backend and in the chat widget.

**Describe the solution you'd like**
We should trim previous messages.

**Describe alternatives you've considered**
When an agent replies, we remove all historical emails under our reply, but we can't ask customers to do that.

**Additional context**
None, fairly obvious what the issue is.

**Comment by sojan-official** [comment]
As described in the original issues, Where there is a long chat thread that gets continued over email, Chatwoot sends out the summary template, which gets sent back to Chatwoot when the contact replies.  Hence a new message gets created as shown below, which doesn't look great when rendered in chatwoot.

<img width="526" alt="Screenshot 2021-08-22 at 11 38 32 PM" src="https://user-images.githubusercontent.com/73185/130365453-66e79df0-8ab9-43cb-b867-75c9f7c4121f.png">

## Acceptance 

Since the conversation history is already there in chatwoot, we aren't concerned about the rest of the thread. let's create the message just with reply alone and strip off the remaining content from previous threads in email while rendering in the UI 

<img width="526" alt="130365453-66e79df0-8ab9-43cb-b867-75c9f7c4121f copy" src="https://user-images.githubusercontent.com/73185/130365659-5329d65d-5d63-4598-b11c-b878bba26775.png">

## Testing 
- test the behavior for conversation continuity in the web widget channel
- test the behavior for conversations in the email channel

**Comment by pranavrajs** [comment]
@sojan-official I think it is better to adopt what Github has been doing such that we hide the content with a button to display the information. There might be cases where someone is forwarding an email content with a long thread of information which would be the first message in the conversation.

An example of Github's behavior can be seen in the following comment. https://github.com/chatwoot/chatwoot/issues/2663#issuecomment-882850431

This needs to be handled in the widget UI as well.

**Comment by sojan-official** [comment]
updated acceptance.
