### ISSUE TITLE
New inbox channel: Instagram DM's & FB comments

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#2096]
**Is your feature request related to a problem? Please describe.**

https://developers.facebook.com/blog/post/2020/10/19/messenger-api-to-support-Instagram/

The messenger API now supports IG DM's as well for approved businesses. We have an approved business and would like to integrate IG DM's as a channel on our Inbox. This is a feature request to support this inbox channel along with FB & IG comments within the dashboard.

**Describe the solution you'd like**
A new IG inbox channel and integrate the comment system from FB and IG into respective channels.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sojan-official** [comment]
https://developers.facebook.com/docs/messenger-platform/instagram/

> We are currently in phase 1 of the global rollout of Instagram Messaging. Instagram accounts with follower count over 10K and under 100K are able to connect to the API. We plan to expand to accounts with between 1K and 100K followers for the next phase in July and include the remaining accounts for the last phase by end of Q3. Please check this page for updates and details of the onboarding steps here.


Let's track this for July - August releases ( phase 2 ) since the majority of chatwoot users fill fit into the 1k-100k followers bucket.

**Comment by thomas-thaulow** [comment]
Any news on this request? We would be very interested in this feature

**Comment by thomas-thaulow** [comment]
@sojan-official Instagram has already implemented it. 

"We are currently in phase 2 of the global rollout of the Instagram Messaging. Instagram accounts with follower count between 1K-100K are able to connect to the API. We plan to include remaining accounts for the last phase by end of Q3. "

**Comment by sojan-official** [comment]
## Context

Instagram messaging has been one of the most asked features in Chatwoot. With the APIs currently open, Let's take up the opportunity to bring in Instagram messaging into Chatwoot as well as improve the overall messenger API experience in Chatwoot.

## Goals

- Ability to connect Instagram page to a Chatwoot Inbox so that the agents can handle messages from Chatwoot inbox instead
- Confer to the Facebook API guidelines. ref: [https://developers.facebook.com/docs/messenger-platform/instagram/](https://developers.facebook.com/docs/messenger-platform/instagram/) ( requirements block ) examples:
    - Ensure that your app respects message delete Webhooks.
- Update product documentation and set up instructions.
- Identify and Improve the Facebook messenger integration overall while working on this if we are missing out on any new messenger APIs

## API references

[https://developers.facebook.com/docs/messenger-platform/instagram](https://developers.facebook.com/docs/messenger-platform/instagram) 

[https://developers.facebook.com/docs/messenger-platform/instagram/features/conversation](https://developers.facebook.com/docs/messenger-platform/instagram/features/conversation) [ At the moment Chatwoot wouldn't sync the existing conversations. we could revisit this ]

## Prerequisites ( Engineering )

- Set up a Facebook inbox on your Chatwoot Installation [ Local ]
- Get familiar with the setup flow.
    - [https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup](https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup)
    - [https://www.chatwoot.com/docs/product/channels/facebook](https://www.chatwoot.com/docs/product/channels/facebook)
- Set up a local development environment with ngrok and have Facebook inbox working .ref : [https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup#developing-or-testing-Facebook-integration-in-your-machine](https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup#developing-or-testing-facebook-integration-in-your-machine)
- Read through the messenger API documentation
- Read through the files in Chatwoot related to the Facebook inbox channel
    - `app/controllers/API/v1/accounts/callbacks_controller.rb` ( the controller that handles authenticating a Facebook page and creating an inbox ) ( Koala gem is used to handle the OAuth and fetch the required tokens for Facebook )
    - `app/models/channel/facebook_page.rb` ( the channel model holding facebook page information )
    - `config/initializers/facebook_messenger.rb` ( file holding configuration for the facebook messenger gem : [https://github.com/jgorset/facebook-messenger](https://github.com/jgorset/facebook-messenger) ) ( the gem add `/bot` end point where we receive Webhooks for messenger events in Facebook events )
    - `lib/integrations/facebook`: various files parsing the Facebook events and creating incoming messages in Chatwoot
    - `app/services/facebook/send_on_facebook_service.rb`  :  creates a message in facebook when agent send a message on chatwoot.

## Assumptions

- Instagram messaging APIs use the same Facebook Messenger API, hence the existing Facebook integration in chatwoot should be able to handle Instagram messages as well, with minor tweaks / fetching additional permissions from Facebook.

---

## Implementation

We will iterate through MVP strategy and continue to improve the implementation based on further user feedback until we can support all the available APIs

- V1: Ability to send and receive Instagram messages : [https://github.com/chatwoot/chatwoot/issues/2850](https://github.com/chatwoot/chatwoot/issues/2850)
- Implement delete message webhooks : [https://developers.facebook.com/docs/messenger-platform/instagram/features/webhook#message-delete](https://developers.facebook.com/docs/messenger-platform/instagram/features/webhook#message-delete) ( to spec )
- Sync Existing conversation to chatwoot when a page is connected ( to spec )
- Implement messenger reaction support ( to spec )
    - Ability for chatwoot to support message reactions
- Support Instagram stories (Story mention and Story Reply) ( to spec)
    - [https://developers.facebook.com/docs/messenger-platform/instagram/features/story-mention](https://developers.facebook.com/docs/messenger-platform/instagram/features/story-mention)
    - [https://developers.facebook.com/docs/messenger-platform/instagram/features/webhook#story-replies](https://developers.facebook.com/docs/messenger-platform/instagram/features/webhook#story-replies)

**Comment by srameshr** [comment]
@sojan-official Along with messages and stories could you also support comments as well? Each comment can be a new conversation under Chatwoot.

**Comment by iammattmartin** [comment]
I asked this question about FB page comments but was told there was no plan. Would be nice to be a full 360 cover for the supported channels.

**Comment by hanthor** [comment]
So you closed the Facebook post comments issue, just hoping that this makes it into the scope of this issues. Also support for deleting other users' facebook post comments too

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/4347
