### ISSUE TITLE
IMAP ingest

### ISSUE THREAD

**Issue by Lewiscowles1986** [chatwoot/chatwoot#2520]
**Is your feature request related to a problem? Please describe.**
As a head of customer success, for a business with a single email support ingress, I would like to support imap email ingest, so that omni-channel support is supported (inbound). So that, the adminstrative overhead of configuring each agent their own email is avoided, a single record of customer communication (ideally per-issue) can be maintained.

**Describe the solution you'd like**
When I added an inbox with email, I sort of expected to need to provide IMAP details, so that like Zendesk, all emails to support could then be further redirected to the appropriate areas using rules and filters.

**Describe alternatives you've considered**
Currently, I can setup SES with an S3 bucket, and use a lambda to classify emails, which can be made available to bespoke apps or an API.

**Additional context**
Seemed like a missing feature. I'm just evaluating the self-hosted edition. Really impressive, but this did seem like a critical missing feature for any business using something like this.

**Comment by azyzio** [comment]
We have just pushed the develop branch to production to discover this feature :) Looks great!

I wonder what how it is compatible with the previous approach of "forwarding" email via mailgun. It seems there are now two separate ways to implement email channel. Are you going to deprecate the "old" one? I'm not really sure what are the differences between them.

Best,
Adam

**Comment by sojan-official** [comment]
@azyzio We will be retaining both options. When SMTP and IMAP are enabled the email channel will use the provided configuration to work.  otherwise, it falls back to the "forwarding" approach.  

SMTP and IMAP configuration is suited for inboxes where you receive relatively fewer emails ( under the provider's sync limits )  and have the advantage that the replies go from the email to which the customer emailed. 

the forwarding approach is recommended when you are handling an inbox with a large volume of emails. 

We are updating the product docs and UI to make this clearer.

cc: @aswindevps
