### ISSUE TITLE
NoMethodError: undefined method contact

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#2553]
https://sentry.io/share/issue/14ccf0894aa646e6810436cd13991a76/

**Comment by HariniKrishnan** [comment]
Hi I would like to contribute for this issue, Shall I go ahead and take it?

**Comment by sojan-official** [comment]
@HariniKrishnan  Please go ahead. Let us know if you need any help.

**Comment by HariniKrishnan** [comment]
Thanks a lot @sojan-official. Sure will reach out for help..

**Comment by HariniKrishnan** [comment]
Hi can you please help me in reproducing this issue?

**Comment by sojan-official** [comment]
@HariniKrishnan The issue occurs when chatwoot processes incoming emails from a contact who already exists in the database and the from address has a different character casing. 

ie `john@acme.inc` exists in the database and In the following line `processed_mail.from.first` returns '`John@acme.inc`
https://github.com/chatwoot/chatwoot/blob/a5bc81b304ac9d0ada34ee360b7642bc53c07793/app/mailboxes/support_mailbox.rb#L59

This would in turn leads to the `create_contact` method call, which would throw the `Email already taken` error, which was suppressed by the line 
https://github.com/chatwoot/chatwoot/blob/a5bc81b304ac9d0ada34ee360b7642bc53c07793/app/builders/contact_builder.rb#L59


-----

Fixes 

- Let's downcase `processed_mail.from.first` before performing the checks and passing it into other methods as an argument.

- Also After logging the error message in the following line, let's also raise the error so that we can catch the issue early.
https://github.com/chatwoot/chatwoot/blob/a5bc81b304ac9d0ada34ee360b7642bc53c07793/app/builders/contact_builder.rb#L59

ps: Setting up an actual chatwoot test environment with email could be tricky. So you could just approach it by writing an RSpec test case.  Let us know if you have questions.

**Comment by HariniKrishnan** [comment]
Thanks a ton for detailed explanation @sojan-official I tried to setup but in vain. Sure will fix and test in rspec.

**Comment by HariniKrishnan** [comment]
hi @sojan-official created PR. can you please review?
