### ISSUE TITLE
"This message was deleted"

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#2586]
When a message is deleted showing "This message was deleted", there should be an option to *not* show this on the widget.

If you're correcting a spelling, to have that show looks very bad.

The same applies to emails, it's looks incredibly unprofessional.

- This _really_ needs to be documented as to what the behaviour is going to be as I would not expect the widget to show the deleted message or this being sent by email, but would expect an admin to still be able to see this.

**Comment by pranavrajs** [comment]
@iammattmartin Makes sense, thanks for the feedback. 

It creates confusion among the users when they send a message and it is deleted by the agent and disappears from the widget. The intention was to avoid this. So that when a user sends a message and the agent deletes it, the user would still be able to see the message with a deleted content. 

For agent side messages, it makes sense to avoid showing it on the widget side and email.

**Comment by iammattmartin** [comment]
I agree with that. If the message deleted is from a user, that is fine - so they know what happened but I would say that staff doing so is to correct an error in a message that they've sent (and before delivery via email) etc.

**Comment by pranavrajs** [comment]
Sure, that makes sense. We will update the behaviour.
