### ISSUE TITLE
Change the `bot` status to `pending`

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2649]
**Backend:**

- Change the enum value from bot to pending.
- Research about the places where bot status is used
    - Add a fallback to pending status in controllers.
    - Look for `bot?` checks in the codebase.

**Frontend:**

- Change all the values from bot to pending.
- Change button text to "Transfer to bot"

**Comment by sojan-official** [comment]
@pranavrajs  Should we decouple the bot references associated with conversation `status` completely. 
ie: instead of "Transfer to bot", We could use "Mark as Pending" 

- Leaves room for using the pending status for use cases outside Bots

Bot integrations can still rely on "pending" status as a marker for the bot's conversation ownership. 
Lets laters add the ability to select 'bots' explicitly in the assignee list  as a way for agents to explicitly mark the ownership

**Comment by pranavrajs** [comment]
@sojan-official Makes sense to me. Let us change the wording to "Mark as pending"
