### ISSUE TITLE
Contacts with same email address are merged although identifier is different

### ISSUE THREAD

**Issue by paescuj** [chatwoot/chatwoot#2811]
**Describe the bug**

I'm using Chatwoot on a portal where the email address of the customers are not yet known. However customers can already be differentiated based on an ID. So when initializing the Chatwoot widget, I'm using this ID to identify customers like this:
```
window.$chatwoot.setUser('<ID>', {
  name: '<Name>',
  identifier_hash: <Hash>,
});
```

With the help of the email collection bot, the customers are then asked for their email address.
As soon as they have entered an email address, a new contact is created in Chatwoot.

Now, when a customer enters the same email address as another customer has before, the contact is merged with the previous contact and all information about the second customer (like custom attributes) are lost.

I know this is a bit of a special case, but I still think this shouldn't happen. 

**To Reproduce**

* Setup new website inbox
* Setup Chatwoot widget like above
* Start a chat as first customer (e.g. with ID "1") and enter an email address
* Start a chat as second customer (e.g. with ID "2") and enter same email address
* You will see that the contact has been merged in the Chatwoot admin interface

**Expected behavior**

There should be two different contacts.

**Environment**

Self-hosted instance, based on develop branch (https://github.com/chatwoot/chatwoot/commit/9e052fd5b2f49bf6fb6cb50872b361160c538d57)

**Comment by pranavrajs** [comment]
@paescuj This is done to reduce duplication in the system. Can you please provide an example use case where the id is different and the email is the same?

**Comment by pranavrajs** [comment]
I see that problem is that the pre-chat form/email collect box is triggered even if the `setUser` method is used. May be we can remove those if the `setUser` method is used.

**Comment by paescuj** [comment]
> @paescuj This is done to reduce duplication in the system. Can you please provide an example use case where the id is different and the email is the same?

The use case is the following:
I have an portal where customers can login and start to chat. The email of the customers aren't known yet.
They can submit their email address via Chatwoot widget (email collection bot).
A customer can be anyone who has a login to this protal, so one person could even have two logins and then submit the same email address.
It is true that this case is not very likely, I know.

But I don't quite get what the "identifier" is used to in Chatwoot then? It makes totally sense to merge a contact when there are two customers with the same email if they **haven't** provided an "identifier".  But don't you think that it should not be merged when they **have** provided a different "identifier"?

> I see that problem is that the pre-chat form/email collect box is triggered even if the `setUser` method is used. May be we can remove those if the `setUser` method is used.

Actually, in my case the email collect box is quite useful 👍

**Comment by sojan-official** [comment]
@paescuj  identifier, email, phone number .. all three of these attributes are considered as unique identifiers in chatwoot.  So these attributes can't be duplicated across contacts. The merge functions assume that they are the same user and merges in this case.  

For this specific case, let me talk to the team and get back.

**Comment by paescuj** [comment]
I see! Thank you very much!

**Comment by sojan-official** [comment]
ref: https://discord.com/channels/647412545203994635/647729773723779073/878258089680306258

>I wasn't able to dig these up.
But I've come to the conclusion that in order to prevent this, maybe reset the cookie in the session, whenever a new setUser value is passed by sdk, instead of merging or updating the current session.
Because in your mentioned case scenario, a shared computer, sometimes yes, the visitor doesn't wait until the sessionReset is fully triggered and closes the page quickly, resulting in old chat session being still stored. So next time they comback, suppose they login to another account (say a client of theirs, or helping a friend, etc), now a new setUser id will be passed, this will then eventually make chatwoot updates current session contact, with the newly passed contact info, or merges them if previous one already exists (email, custom attributes, etc).
So I think it would be better to have chatwoot decides to preemptively resets the session, if a new setUser id value is passed that's different from the value of the one saved in the previously existing session.

**Comment by sojan-official** [comment]
note: We will revisit the contact merge action in cases where a contact identifier is already provided.

**Comment by RuiGuilherme** [comment]
>This is done to reduce duplication in the system. Can you please provide an example use case where the id is different and the email is the same?

I have a curious situation, I don't know if it will enter on this issue.

I have 2 systems for different locations (States), and I can have the same user registered in two states and can have the same e-mail.

Considering the e-mail duplicity, my client is able to see the message on both systems.
Look: https://youtu.be/D3QqpRZY_qw

'Identifier' has the same problem:

**System 1**
|id|username|password|email|
|--|--------|--------|-----|
|1|test|hash|test@test.com|

**System 2**
|id|username|password|email|
|--|--------|--------|-----|
|1|another user|hash|another@random.com|

But I can solve this just concant **"X"+user.data.id** for first system and **"Y"+user.data.id** for the second system.


Now for e-mail:
**System 1**
|id|username|password|email|
|--|--------|--------|-----|
|53|test|hash|test@test.com|

**System 2**
|id|username|password|email|
|--|--------|--------|-----|
|121|test|hash|test@test.com|

As you can see, they are two different users on different systems with the same emails. I could even use the same solution in the email, but I believe that it would harm the functioning of the chat.

I believe that each inbox should have its own user base.

**Comment by sojan-official** [comment]
@RuiGuilherme contacts in chatwoot are shared across inboxes.  This lets us show conversations from various channels like WhatsApp, Email, etc under a single contact in chatwoot. 

In your case, you could try the following

- Instead of using the identifier,  use the customer email as the identifier in your setUser call. 
- create separate website inboxes for each system. 
- the customer will have separate chat sessions 
- you agents will be able to see conversations from the same person across both systems under the same contact.
- you could additionally use custom fields to add the user id information in both the systems to the contact if it's relevant for customer support.

**Comment by sojan-official** [comment]
closing this issue in favor of https://github.com/chatwoot/chatwoot/issues/4728
