### ISSUE TITLE
Add documentation on how chatwoot can be deployed to production

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#282]
Add documentation on production deploy 

- heroku

1.  one click deploy

- docker

1. basic instructions

**Comment by sojan-official** [comment]
Based on the feedback we received. seems like users are finding it hard to understand what to do after doing something like a heroku deployment. So let's write clear instructions on available options to deploy and also the set up after deploy 

- [ ] Deploy to Heroku instruction
- [ ] Instruction on how to login
- [ ] Adding Agents

**Comment by alfredfrancis** [comment]
this is very much needed

**Comment by Skeyelab** [comment]
I agree with the need for this.  I use Heroku daily and find that some of the settings that ChatWoot uses are not common on Heroku.  For example, we technically shouldn't need to define the individual Postgres credential values and we should use `ENV["DATABASE_URL"]` instead. (however, that is a different discussion)

**Comment by pranavrajs** [comment]
@Skeyelab ENV["DATABASE_URL"] should work automatically.

**Comment by bobmulder** [comment]
Hi there! 

Is there any documentation about how to deploy Chatwoot for production? https://www.chatwoot.com/docs/quick-setup seems to be meant for development and https://www.chatwoot.com/docs/installation-guide-ubuntu too...

**Comment by vishnu-narayanan** [comment]
Hi @bobmulder, We understand it's a little rough around the edges :sweat_smile: and are working on a much more accessible documentation detailing production setup. It should be live soon. Thank you.

**Comment by bobmulder** [comment]
Thank you for your reply @vishnu-narayanan, I understand completely. Chatwoot looks promising (one of the best open-source alternatives available), but as you said, _it's a little rough around the edges_. All the best and I'll keep following you guys :)

**Comment by pranavrajs** [comment]
Reopening this as the documentation is not added, only the scripts were added.

**Comment by AdityaAnand1** [comment]
Any updates on this? 

Right now I'm stuck on this with no idea where to go

![image](https://user-images.githubusercontent.com/13274079/83501840-5987fa00-a4de-11ea-83c0-e8fbdb924bc3.png)

And here also, I arrived only by random trial and error, my client and backend are both glitching out, getting stuck. Server randomly 500-ing.

Definitely not the experience we want. Can we fast track the documentation? And maybe set up sane defaults so that users can just deploy, stick a script in frontend and off we go <= This would be the best experience.
