### ISSUE TITLE
Start documenting APIs

### ISSUE THREAD

**Issue by sony-mathew** [chatwoot/chatwoot#298]
Currently, we do not have documentation on any API endpoints that Chatwoot supports. We should start documenting these API endpoints. 

As a starting point for this, we should use any standard tooling to document these endpoints. We could use swagger to do this.

The idea is to initialize swagger docs here (for one simple API) and provide a way to contribute to this incrementally.

This should provide a base for adding APIs incrementally and easily to maintain.

This should serve as API docs for all clients which are built on top of this platform.

**Comment by mukesh4139** [comment]
We have a few gems which can create API documentation using the acceptance specs without any effort.

Specs and Documentation both can be covered with this approach.

https://github.com/zipmark/rspec_api_documentation
https://github.com/jejacks0n/apitome

**Comment by sojan-official** [comment]
@mukesh4139  I am cool with generating the API documentation from specs.  
another option is https://github.com/rswag/rswag if we are going to rely on swagger.   

But I would like an approach where some API documentation is embedded into the code via some sort of annotation, so whoever makes changes to the API wouldn't forget to update the same for API as well.  

https://github.com/fotinakis/swagger-blocks . looks interesting, but it seems to require some sort of a DSL  which might scare new contributors.  

let's explore further before making a call on this since it should be something that we can use longterm

thoughts :  @sony-mathew  @subintp  @pranavrajs  @manojmj92

**Comment by sony-mathew** [comment]
@sojan-official  I think for a V1 of this we can go with normal Swagger documentation and take it from there depending on the maintainability and ease of access.
