### ISSUE TITLE
[CW-1568] Trigger Dialogflow Bot when opening the chat.

### ISSUE THREAD

**Issue by valentinwinkelmann** [chatwoot/chatwoot#2993]
**Is your feature request related to a problem? Please describe.**
If a Dialogflow bot is used and the visitor opens the chat, he must first write something to which the bot responds. This leads to the fact that the visitor first of all assumes he has a simple live chat in front of him, through which he reaches a human person. So he will most likely write wildly and think he is writing with a human.

**Describe the solution you'd like**
It would be useful if a bot would be triggered as soon as the chat opens, this makes it immediately clear to the visitor that it is a bot that can now assist him. For example, as soon as the chat opens, the visitor can be greeted immediately and a selection of options can be provided via interactive messages.

<sub>[CW-1568](https://linear.app/chatwoot/issue/CW-1568/trigger-dialogflow-bot-when-opening-the-chat)</sub>

**Comment by sojan-official** [comment]
note: trigger `welcome` event on widget open for Dialogflow. 

ref: https://cloud.google.com/dialogflow/es/docs/intents-default#welcome

**Comment by sojan-official** [comment]
ref: https://cloud.google.com/dialogflow/es/docs/contexts-input-output#input_contexts
set inbox name, contact name, etc as context variables so that advanced intents can be configured.



ref: https://discord.com/channels/647412545203994635/848225049059917834/958016971000135700
> My thinking at the moment is to use the same bot for different users, however each interaction has to make queries to an api via dialogflow and must be limited to only data for that specific user/channel.
So to summarize.
3 different inboxes use the same bot.
A user visits a chats via (for example the web) but for a specific inbox, that user's conversation should be handled by dialogflow, dialogflow should already know and set a context variable based on which inbox the conversation is in, and pass that along to an api to limit the query.

> Hope this helps.

**Comment by iammattmartin** [comment]
I'd say without this, it makes DF a bit useless. As @valentinwinkelmann says, customers only get this once they enter data which is often after they spend time writing their initial query. 

This is poor CX and just leads to frustration.

**Comment by iammattmartin** [comment]
@sojan-official bit sad this is not planned when it makes DF unworkable for the reasons others have stated.

How do you think we should invoke this without the user having to repeat themselves.
