### ISSUE TITLE
NoMethodError: undefined method `sid' for nil:NilClass

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#3029]
<img width="1200" alt="Screenshot 2021-09-17 at 10 55 35 AM" src="https://user-images.githubusercontent.com/12408980/133729184-2e38a085-6c93-41d5-b759-ec621f6c9607.png">

**Sentry error details**

https://sentry.io/share/issue/33c21d44e9ed47a8ad283ce0eebb4c2f/

<img width="786" alt="Screenshot 2021-09-17 at 10 46 01 PM" src="https://user-images.githubusercontent.com/12408980/133828225-b5c6a613-c261-4c0d-91a6-67628b61b5dd.png">

**Comment by muhsin-k** [comment]
@tejaswinichile Could you please look into this?

**Comment by tejaswinichile** [comment]
I couldn't dig more as the mentioned message with message_id = 6155 https://sentry.io/organizations/chatwoot-7d/issues/2655142384 is not available in the system.
The issue is with: Twilio client which couldn't create SMS and we are trying to extract the `sid` from non created message. 
So to resolve this: 
1. if we face the issue/exception with Twilio we should grab it in sentry.
2. And update the message-id only when the Twilio message is present with sid.
 Raised a PR here; #3049
