### ISSUE TITLE
feat: Update APIs for contact avatar

### ISSUE THREAD

**Issue by Stephen-Lobo** [chatwoot/chatwoot#3428]
**Describe the bug**

The thumbnail string for Contact is not getting updated. 

**To Reproduce**

1. Send PUT / PATCH request to update thumbnail of the contact through API
2. All other fields get updated, except THUMBNAIL

**Additional context**

Tried through POSTMAN and also through local PHP API

**Comment by pranavrajs** [comment]
@Stephen-Lobo Can you please share the payload you are using?

**Comment by Stephen-Lobo** [comment]
I am tried to use all PUT/PATCH/POST for {{host}}/{{api_version}}/accounts/{{account_id}}/contacts/some_contact_id through POSTMAN

with simple payload "
{
  "thumbnail": "url_of_some_picture.png"
}

This doesn't works. 

if I send similar request with complex payload like :

{
  "thumbnail": "url_of_some_picture.png",
   "phone_number": "1232323",
    "otherparam": "param_options"
}

All other param gets updated except thumbnail. 

Please try to test at your end.

**Comment by sojan-official** [comment]
## Current behavior
- If an `avatar_url` parameter is passed in `setUser` method of widget SDK, chatwoot will update the contact Avatar. 
- if no `avater_url` is passed. But the contact has an email address, Chatwoot renders the gravatar for the contact if present ( chatwoot doesn't locally cache the gravatar. it generates the hashed URL for gravatar in backend instead ) 
ref: https://github.com/chatwoot/chatwoot/blob/9103fbbddeb24c2b5dba10f75087cb9b2ca6ef22/app/models/concerns/avatarable.rb#L17

## Suggested Changes 
- Contacts create and update endpoints in application APIs should be able to accept avatar attachment parameters [form data] 
- Contacts create and update endpoints should be able to accept the avatar_url parameter if users wish so. use  ContactAvatarJob
- update the API swagger docs 
- Instead of returning gravatar URLs on the fly, cache them as attachments on the contact. 
  -  this will stop the 404 errors while loading the dashboard 
  -  gives users the ability to remove avatars when deemed inappropriate. 


@Stephen-Lobo  I looked into the code and at the moment chatwoot application APIs don't support updating the contact avatar.  We will take this up for future releases.

**Comment by akhilgkrishnan** [comment]
@sojan-official  I can pick this up

**Comment by sojan-official** [comment]
@akhilgkrishnan  please go ahead

**Comment by hasanbasri1993** [comment]
@akhilgkrishnan why removed ?

**Comment by giquieu** [comment]
I can implement this function.
@sojan-official  what do you think?

**Comment by hasanbasri1993** [comment]
> I can implement this function.
> 
> @sojan-official  what do you think?

Please implement this

**Comment by giquieu** [comment]
Hey,
@sojan-official, I sent a PR, could you please check if it meets the suggestions?

**Comment by sojan-official** [comment]
@giquieu  Thanks for the effort. We will take a look and take it forward.
