### ISSUE TITLE
using apache2 insted nginx

### ISSUE THREAD

**Issue by Alarees** [chatwoot/chatwoot#3465]
i am tried to install chatwoot server on my server (ubuntu 20.04 ), but i had issue, and i think it's becouse chatwoot server trying to use `nginx` server and nginx conf, and nginx in my server not working
who to solve this issue ?

**Comment by vishnu-narayanan** [comment]
@Alarees Could you please update the issue description with more context ? Please follow the below template.

----
**Describe the bug**

A clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**

A clear and concise description of what you expected to happen.

**Screenshots**

If applicable, add screenshots to help explain your problem.

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

Share the server logs to debug the issue further

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**

Add any other context about the problem here.

**Comment by Alarees** [comment]
solved in #3470
