### ISSUE TITLE
timeoutable on devise in config does not work for agent login timeout

### ISSUE THREAD

**Issue by rahulmr** [chatwoot/chatwoot#3467]
**Describe the bug**

timeout_in config for devise does not work on self hosted chatwoot application

**To Reproduce**

In self hosted chatwoot applications when I change config\initializers\devise.rb
```
  # ==> Configuration for :timeoutable
  # The time you want to timeout the user session without activity. After this
  # time the user will be asked for credentials again. Default is 30 minutes.
  config.timeout_in = 5.minutes
```
**Expected behavior**

Agent must be signed out automatically in 5 minutes of in activity.
This is not happening.

**Environment**

Chatwoot develop branch on ubuntu using docker-compose - ENV development

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS 
 - Browser: chrome
 - Version: 91.0.4472.124 

**Additional context**

I am not sure whether I am doing it properly, if you think I am missing something please let me know.
When I sign in as Agent , I expect that once a particular time passes and the agent is in active or idle then his session must be forced logged out.

**Comment by tejaswinichile** [comment]
We haven't initialized `devise: timeoutable` for user model, that's why it's not working. 
You will need to add `devise :timeoutable, timeout_in: XX.minutes` in user model.

And we have `devise :rememberable` configured it work it conflicts with timeout https://github.com/heartcombo/devise/blob/main/lib/devise/hooks/timeoutable.rb#L26

If you still want to change that in your self-hosted version you can remove the rememberable and enable timeoutable as shown in https://github.com/heartcombo/devise#configuring-multiple-models

I am closing this issue as it is not specific to the product and answered how to get it fixed for the self-hosted version.

cc @sojan-official
