### ISSUE TITLE
Can't display advanced filters

### ISSUE THREAD

**Issue by sanjayws** [chatwoot/chatwoot#3523]
**Describe the bug**

I've setup 3 instances of CW on Ubuntu 20.04 using the linux script. On all 3 instances, i can't seem to find the advanced filters as stated in https://www.chatwoot.com/docs/product/others/advanced-conversation-filters.

Any advice would be highly appreciated. Thank you.

![image](https://user-images.githubusercontent.com/25242465/145150041-d4c2827a-afb5-43ce-a970-8a621b86b2ba.png)

**Comment by sojan-official** [comment]
@sanjayws advanced filters in UI will be available in our upcoming release.  the Linux installation will install the last stable release. 

if you want to give it an early try. 

ref: https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#upgrading-to-a-newer-version-of-chatwoot

instead of the command `git checkout master && git pull` do 

```
git checkout develop && git pull
```
