### ISSUE TITLE
messages from a telegram bot don't get through

### ISSUE THREAD

**Issue by danielzzz** [chatwoot/chatwoot#3813]
Hi, 

**Describe the bug**

I have connected my telegram bot, but when I send messages to it, they don't get through to chatwoot. 
shall I do something more? 
the account seems to be active an properly configured in chatwoot.

**To Reproduce**

1. Add a new telegram inbox
2. input the key
3. the bot is detected and added as an inbox
4. try sending a message from telegram to the bot

**Expected behavior**

I would expect messages to get to chatwoot. however, nothing happens.

![image](https://user-images.githubusercontent.com/351916/150175775-a45865a4-914b-4a98-bea2-c073cf8808ae.png)

![image](https://user-images.githubusercontent.com/351916/150175848-444dbb62-56f2-48bc-81a0-f60158b3dde3.png)

**Comment by danielzzz** [comment]
hi, it's a docker-compose version.

I attach logs here. 
basically I opened it, added a sample newly created bot. then sent a message to the bot from my telegram account.

sorry I don't know ruby very well, to see if there is some problem here..
[logs.txt](https://github.com/chatwoot/chatwoot/files/7899254/logs.txt)

thanks, dan

**Comment by tejaswinichile** [comment]
According to the logs I don't see any message reaching the telegram message controller endpoint.

Few questions:

1. Are you testing this on your local machine?
2. Have you gotten the bot token as mentioned in the doc for telegram https://www.chatwoot.com/docs/product/channels/telegram/
3. Have you added your local URL to the telegram bot? Because you would need to do that with ngrok to make the bot token work. 

If not already please follow https://www.chatwoot.com/docs/product/channels/telegram/

**Comment by danielzzz** [comment]
hi,

1) yes

2) yes, all good, I have everything that appears there

3) this is probably what I'm missing, but how should I configure ngrok here? would you please point me to the docs how to configure it?

thanks a lot, dan

**Comment by danielzzz** [comment]
ok, I got it to work.

followed the steps here
https://www.chatwoot.com/docs/contributing-guide/telegram-channel-setup

deleted the bot from chatwoot and registered it again. 

verified the public url appears here:
https://api.telegram.org/bot{bot-auth-hash}/getWebhookInfo

and it seems to be working.

thanks a lot for your help!
dan
