### ISSUE TITLE
feat: Option to disable gravatar usage

### ISSUE THREAD

**Issue by freddy36** [chatwoot/chatwoot#3853]
Due to EU GDPR regulations the current requests to gravatar are problematic (We would have to ask the chat visitor for consense first).

Due to this we would like to suggest an option to disable the usage of Gravatar completely.

**Comment by iammattmartin** [comment]
Might be worth checking this as you'll only get the gravatar if they are already supplying their email, which you'd need their permission to do in the first place (i.e storage).

**Comment by freddy36** [comment]
If an agent hasn't set an avatar, the client will do an gravatar request for the agent too.
The client request can be suppressed by setting some dummy `avatar_url` with `setUser()`.

**Comment by jaime-rivas** [comment]
We are in a similar situation. It would be great to have the option to fully disable the usage of Gravatar.

Thanks for the great work!

**Comment by ffroehlcke** [comment]
Same her! Please add an option to disable the usage of Gravatar.

**Comment by sojan-official** [comment]
@jaime-rivas  @ffroehlcke  Could you share more details behind the requirement to disable gravatar? 
Is it aesthetics, or are there compliance issues that you are facing?

**Comment by marcel-necker** [comment]
Here are a few things to consider:
- Compliance: As mentioned by @freddy36, this could be a compliance issue since a request is made to an external URL (gravatar.com) at repetitive intervals. This could potentially be used for tracking or analytics purposes (e.g. like Google Fonts does) that require an explicit user consent
- Aesthetics/Buggy: A request every minute which results in a 404 not found error in console doesn't seem ideal
- Usage: Gravatar is not that well known in some regions or customer audience. So they probably don't have an account there or use Gravatar at all

A way to optionally disable or enable (initially disabled) this feature would be nice!

**Comment by jaime-rivas** [comment]
@sojan-official I concur with @marcel-necker

**Comment by ffroehlcke** [comment]
@sojan-official Same here

**Comment by KevinEduardo** [comment]
Same, gravatar also kinda sucks tbh

**Comment by sojan-official** [comment]
Thanks a lot for the feedback. We will introduce an environment variable, which lets you disable gravatar once https://github.com/chatwoot/chatwoot/pull/4719/ is merged
