### ISSUE TITLE
failed to initiate new chat session on Messengger Inbox that integrate with Dialogflow

### ISSUE THREAD

**Issue by aldhielman** [chatwoot/chatwoot#4008]
I have problem with my Messenger Inbox with Dialogflow integration to handle intent. I've apply Agent Handoff mechanism as describe in [here](https://www.chatwoot.com/docs/product/channels/live-chat/integrations/dialogflow#creating-a-handoff-intent) . After particular session chat is Resolved by our agent than i try to send new message from Facebook but it seems no Dialogflow Bot to answer (status:pending) instead chat get status **open** and directly assigned to agent that handle those session before.

this some erro log from sentry when i try to create new session(message) from facebook after Resolving conversation before
![image](https://user-images.githubusercontent.com/16577318/154384212-b0d4b7c8-caec-4c50-a240-0e5595974576.png)

I assume it happened becaue new message (after Resolve action) didn't create new Conversation. I know message came from same "person" so Chatwoot didn't create new conversation record for same "person"/sender, am i right ?

Additional info:
It work perfectly on WebWidget Channel

**Comment by pranavrajs** [comment]
@aldhielman The sentry error you mentioned is fixed in https://github.com/chatwoot/chatwoot/pull/3978.

Let me summarize the issue here. 

1. The conversation was handled by the bot.
2. It was transferred to an agent via Handoff.
3. Then it was resolved by the agent.
4. Customer sends a message again, it goes to the agent instead of a bot.

If this is the issue, the behavior is as per our current design, the bot would only handle the conversations that are in pending status. When a message comes to a resolved conversation, the default action is to put the conversation to open, not to transfer it to an agent. If you want the bot to respond to the query, then you can mark the conversation as pending instead of resolving it.

Since Facebook doesn't have multiple threads of conversation, we deal with it as the same. A new message wouldn't create a new conversation, instead, it would open the previous one.

Hope this helps.
