### ISSUE TITLE
Add rules based on the attribute update

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4181]
As an agent, I’m not able to add rules based on an attribute change of a contact or conversation. 

For eg: If the conversation Priority (a custom attribute) is changed from P1 to P2, assign it to the P2 Issues team. 

Missing event, attribute changed - conversation.updated would work here if the payload has which attribute changed.

**Comment by tejaswinichile** [comment]
@pranavrajs where do we mention the attribute changed?
We have conversation.updated in place but we don't mention the data updated or any payload in the automation rule.

**Comment by pranavrajs** [comment]
@tejaswinichile As discussed we just need to add the condition for attribute change.

 [ Attribute Changed ] - [Attribute Name] - [From] - [To]

From and To are optional.

**Comment by tejaswinichile** [comment]
```
"conditions": [
            {
              "attribute_key": " #company",
              "filter_operator": "attribute_changed",
              "values": { from: **first_val**, to: **second_val** },
              "query_operator": "OR"
            },
            {
              "attribute_key": "is_priority_customer",
              "filter_operator": "equal_to",
              "values": [true],
              "query_operator": null
            }
]
```

@pranavrajs @fayazara I am going with the above-mentioned hash for the `attributed_changed` operation.

**Comment by sojan-official** [comment]
@tejaswinichile We will have to make some changes to the condition filter service I believe for us to accommodate this feature. Rather than the current model where we query all the conversations where the rules match and then check whether the conversation is present in that array,  we would have to switch to a model where we validate the object against each rule. 

another option would be to introduce something like paper_trail gem which retains the history of status changes. 
let's sync up over a call for this.
