### ISSUE TITLE
Providing a bad phone number should not break PATCH for other attributes (email, name, etc.)

### ISSUE THREAD

**Issue by Vadorequest** [chatwoot/chatwoot#4233]
I tried to provide the phone number, but it crashed my whole integration with "422 (Unprocessable Entity)" error.

PATCH https://app.chatwoot.com/api/v1/widget/contact?website_token=DJGn3WJ5dyMCUPh3rQHRJ8r6&cw_conversation=eyJhbGciOiJIUzI1NiJ9.eyJzb3VyY2VfaWQiOiJmMTJjYzhmYy02MmEwLTQ1MjMtYTdmMS1hYmM0MjQ3MzMyZmIiLCJpbmJveF9pZCI6MTI0NDZ9.rIiRaI9CJk69R7mZVdqT1pp63ruw9DZ9X_BU92sdhU4 422 (Unprocessable Entity)

Looking into the network logs, I saw that:
message: "Phone number should be in e164 format"

It's not mentioned in the doc.

Also, and that's the main point, providing a bad phone number should NOT cancel the whole PATCH query, it should just ignore the phone number.

Right now, because I provided a bad phone number (not E164), it didn't store the email/name/company either, because the whole PATCH query failed altogether. This is not the best behavior.

Can you:

- Update the documentation to mention the phone_number format that should be used
- Change your PATCH handler so that a bad phone number doesn't break the whole thing?

Also, converting a phone number to E164 is not a trivial task to do, especially when being limited by using no-code tools.

**Comment by pranavrajs** [comment]
@muhsin-k Please take a look at this change.

**Comment by pranavrajs** [comment]
@Vadorequest Just to make sure that we understand the issue properly.

1. Chatwoot requires you to send the phone number in the specified format. We don't allow duplicate number as well the number in a different format as it would fail the integration we have in place. Changing this constraint might be hard.

2. We will update the documentation for the same.

3. I understand that you would have issue with the data you would have collected from different tools. Would it be okay if you use a custom attribute to save phone number instead of the default phone number if you cannot convert it to e.164 format.

**Comment by Vadorequest** [comment]
I'm not asking you to change the phone number format, I guess if you chose to use E164 it was for a good reason.

But what you could do, is change your PATCH implementation so that if any of the attribute sent is not valid, it wouldn't invalidate the whole payload, but only the concerned attribute.

For instance, if I send name + phone number, if the phone number is in a bad format, the name should still be updated.

Otherwise, a single misstep on our side would break the whole integration, as no data about the user would be updated.

**Comment by pranavrajs** [comment]
@sojan-official Thoughts on the above implementation?

**Comment by sojan-official** [comment]
@pranavrajs  I think skipping the invalid attributes would make the integration much more accessible than a hard failure since we are not providing any callbacks to know whether the call was successful.
Some data getting stored would be a better outcome than no data saved.

ref: #https://github.com/chatwoot/chatwoot/issues/1229

**Comment by pranavrajs** [comment]
@sojan-official Sounds good, is there anything more required to pick this ticket? If not, let take it to the next sprint.

**Comment by sojan-official** [comment]
@pranavrajs should be good to go. Let's remove the invalid params prior to save.

**Comment by muhsin-k** [comment]
@sojan-official Should we consider the `email` attribute too?

**Comment by Vadorequest** [comment]
I don't know what are the specs for the email, but I would say yes for it,
too.

**Comment by sojan-official** [comment]
@muhsin-k let's do it for all attributes supplied by `setUser`
