### ISSUE TITLE
unknown characters(????) in email channel

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#4381]
please see this below image i think there's issue in email body  characters for Arabic language

![image](https://user-images.githubusercontent.com/20530550/161550164-c94d65de-70e1-4cc7-9128-f90c3a9fa019.png)

**Comment by pranavrajs** [comment]
@voko3456 Would it be possible to send the email export to hello@chatwoot.com? Here is a guide for the same. https://support.google.com/mail/answer/9261412?hl=en

@tejaswinichile Please take a note of this issue.

**Comment by sojan-official** [comment]
possible duplicate : https://github.com/chatwoot/chatwoot/issues/4094

**Comment by pranavrajs** [comment]
@sojan-official It could be a duplicate.

**Comment by tejaswinichile** [comment]
@sojan-official @pranavrajs I have sent the emails n this conversation: https://staging.chatwoot.com/app/accounts/3/conversations/2431

1. once by setting my Gmail language to Arabic
2. And second by directly copying the text from the internet and sent in while the Gmail language setting was set to English.

We do have support for UTF-8 characters, but as I was going through some documents, some mailer uses UTF-16 encoding if they are only using the Arabic language.

I have tested with the test cases where I set the charset to UTF-16 and added the Arabic language content and it sent me a stream of `???` characters, but when I sent the same email content with UTF-8 charset it worked well.

@voko3456 Can you forward the email to us, maybe removing the confidential data, because I think the issue is in the charset of the email?

**Comment by voko3456** [comment]
> @sojan-official @pranavrajs I have sent the emails n this conversation: https://staging.chatwoot.com/app/accounts/3/conversations/2431
> 
> 1. once by setting my Gmail language to Arabic
> 2. And second by directly copying the text from the internet and sent in while the Gmail language setting was set to English.
> 
> We do have support for UTF-8 characters, but as I was going through some documents, some mailer uses UTF-16 encoding if they are only using the Arabic language.
> 
> I have tested with the test cases where I set the charset to UTF-16 and added the Arabic language content and it sent me a stream of `???` characters, but when I sent the same email content with UTF-8 charset it worked well.
> 
> @voko3456 Can you forward the email to us, maybe removing the confidential data, because I think the issue is in the charset of the email?

@voko3456 I already send it to hello@chatwoot.com
