### ISSUE TITLE
bug: Files in Whatsapp arrives with a different name

### ISSUE THREAD

**Issue by mattiamarras** [chatwoot/chatwoot#4481]
Hi, if I send a file via WhatsApp to the end customer it arrives with a different name (null.pdf or Untitled).

**Comment by sojan-official** [comment]
@mattiamarras  could you add more details on which provider you are using for whatsapp ?

**Comment by mattiamarras** [comment]
Ciao Sojan, i am using https://www.360dialog.com/, using the native integration of Chatwoot.

**Comment by sojan-official** [comment]
### Notes 

ref: https://github.com/chatwoot/chatwoot/blob/a788e7ac7ab4b8bc358981124694676b413849fd/app/services/whatsapp/providers/whatsapp_360_dialog_service.rb#L81

- [ ] Replace caption with filename when attachment type is document
- [ ] Send message content as a separate message before the attachment ( since whatsapp doesn't support message and attachments attached together )
- [ ] Implement the same for whatsapp cloud
- [ ] Verify behaviour of audio messages for 360dialog when caption is present: ref: https://github.com/chatwoot/chatwoot/issues/5078

**Comment by vagner-dias** [comment]
@sojan-official - FYI - I am using Whasapp Cloud API and I am having the same synptom.

If I send this on chatwoot:
![image](https://user-images.githubusercontent.com/86367839/201949151-8eb3c485-9011-4875-a12e-abd617f784ac.png)

the user gets this:
![image](https://user-images.githubusercontent.com/86367839/201949355-792b954f-98e0-4fee-9cb4-7ef5325abb59.png)

**Comment by giquieu** [comment]
Hello @sojan-official 
I sent a PR about this Issue: https://github.com/chatwoot/chatwoot/pull/5907
Could you please review the PR? Also a test with 360Dialog.
I tested it only on WhatsApp Cloud and it's working.

**Comment by sojan-official** [comment]
@giquieu  Thanks a lot for working on this. We will have it tested and merged.
