### ISSUE TITLE
doc: How to associate contact with inbox via API

### ISSUE THREAD

**Issue by hiagodotme** [chatwoot/chatwoot#4670]
I didn't find in the documentation how do I associate a contact with an inbox through the API. When I try to start a conversation only email inbox is displayed.

**Comment by sojan-official** [comment]
You can associate a contact to an inbox while creating the contact through API by specifying an inbox ID. 
https://www.chatwoot.com/developers/api/#operation/contactCreate

Other than that you will only be able to associate contacts to the inboxes of types email, SMS, WhatsApp, and API channel while creating a new conversation. 
https://www.chatwoot.com/developers/api/#operation/newConversation ( specify inbox id and source id )

learn more about contact models in chatwoot here: https://github.com/chatwoot/chatwoot/wiki/Building-on-Top-of-Chatwoot:-Importing-Existing-Contacts-and-Creating-Conversations

 For other channels like Facebook, Twitter, etc  you will have to wait for the webhook event from the external channel for the contact to be created in Chatwoot. 


--- 

- For the start conversation option, only the email channel is displayed because the contact will only have the email attributes
- if you have a phone number associated with the contact and have SMS or WhatsApp channels, then it should also be available in the dropdown

**Comment by alchemistake** [comment]
I have an api problem. I'm trying to create new Conversations. Source id is coming from contact no:49 and inbox:4 but i specify inbox:6 while creating new conversation. The conversation goes to inbox:4. Am i doing something wrong or is there a problem?

**Comment by sojan-official** [comment]
@alchemistake  . ref: https://github.com/chatwoot/chatwoot/wiki/Building-on-Top-of-Chatwoot:-Importing-Existing-Contacts-and-Creating-Conversations 

When you specify the source id, chatwoot deduces the inbox id from the source id. you will have to create a new source id if you want to create conversations against another inbox.
