### ISSUE TITLE
Account number in URL

### ISSUE THREAD

**Issue by grupale** [chatwoot/chatwoot#5002]
I would like to know if the following behavior is correct
When I login with agent user "A" the URL to the dashboard is like "mydomain.com/app/accounts/1/dashboard"
Then if I enter with another agent user "B" the dashboard URL is also "mydomain.com/app/accounts/1/dashboard"

For inboxes, the URL defines a number for each, eg "/inbox/13", "/inbox/12" shouldn't it do the same for each user account? eg "accounts/2/dashboard" , "accounts/3/dashboard"

Is there a way to set this?

Thanks!

**Environment**

Self hosted Docker installation

**Comment by sojan-official** [comment]
`Account` in Chatwoot refers to an organization
User in Chatwoot is scoped under a different model `User` 

Since you are accessing the inboxes within the same account `1` in this case, Even though the users are different, the URL doesn't change. We don't have references to the user Id in any part of the URL.
