### ISSUE TITLE
Single conversation for API inbox

### ISSUE THREAD

**Issue by weixingp** [chatwoot/chatwoot#5038]
**Is your feature request related to a problem? Please describe.**
Difficult to produce single conversation behaviors in the API inbox. 

**Describe the solution you'd like**
A single conversation option just like SMS / WhatsApp.

- UI: Has the option to decide if a new conversation should append to an existing conversation. (VS starting a new conversation)
- UI: Has the option to continue resolved conversation, and set it to open again automatically. (VS starting a new conversation)
- API: Using the same create conversation API, follow the options set in the UI. (eg. if the single conversation option is turned on, create conversation API will not create a new one, but append the message to the current conversation.)

**Describe alternatives you've considered**
For now, in order to produce the behavior, the following calls to the API got to be made per message:

1. Get the contact by ID/attributes
2. Get the contact conversations, get the ID of the first one (which is also inconsistent, the order isn't preserved)
3. If no conversation found, start a new conversation and get the ID.
4. Send a message to the conversation

Using the above works for now, but the agent still has the ability to start a new conversation, which can be undesirable.

**Additional context**
Nil.

**Comment by pranavrajs** [comment]
@weixingp I don't think there is a limitation in Chatwoot to achieve this. You can use it for both single-threaded and multi-threaded conversations. You can save the conversation_id on your end instead of searching in contact_conversations. This use case is too specific to be provided as an option.

Please feel free to reopen the conversation if you have further thoughts.
