### ISSUE TITLE
Password reset request api error message

### ISSUE THREAD

**Issue by jemilu2** [chatwoot/chatwoot#5134]
**Background**
The current api at (/auth/password) returns the following error message
`{"message":"Uh ho! We could not find any user with the specified email."}`.

That reveals information about users on a particular chatwoot instance.

The current best practice is to make the request appear to have succeeded
regardless of whether a user was found or not. 

**Feature Request**

- Change the error message to the following
  `Please check your email inbox for a link to complete the reset.`

- Modify UI to hide the form and show the above  message

**Comment by pranavrajs** [comment]
@jemilu2 I'm not sure whether this would be helpful. The system would throw an error when the user signs up, and the same information is available in that API.

Also, we have a rate limit configured so that a random script cannot scrape this information. 

> Please check your email inbox for a link to complete the reset.

I'm not sure what this means. Can you please elaborate?

Closing this as the reply solves the query. Please feel free to reopen this if it is not the case.
