### ISSUE TITLE
Auto Reconnect WebSocket Connection

### ISSUE THREAD

**Issue by julienmarie** [chatwoot/chatwoot#5182]
**Is your enhancement request related to a problem? Please describe.**
If there is a network interruption, the websocket connection is breaking up and needs to be manually restored. Which means that if the Agent is not monitoring at that moment his window ( which can happen when working on other tasks ), he could be missing tickets.

**Describe the solution you'd like**
If the software could try to reconnect automatically

**Describe alternatives you've considered**
None

**Additional context**
Our team exclusively works from home and/or remotely and network conditions are not consistent.

**Comment by pranavrajs** [comment]
@julienmarie Are you using a self-hosted installation?

**Comment by julienmarie** [comment]
Hi @pranavrajs . Yes it's self hosted via Docker-Compose on ubuntu 20.04, version v2.7.0.

**Comment by julienmarie** [comment]
As the code is detecting when the websocket is disconnected, would not it be possible to try to reconnect again when this happen?
something like that ?:

```     
window.bus.$on(BUS_EVENTS.WEBSOCKET_DISCONNECT, () => {
     const { pubsub_token: pubsubToken } = this.currentUser || {};
     vueActionCable.init(pubsubToken);
}) 
```

**Comment by sojan-official** [comment]
@julienmarie  Chatwoot reconnects to the WebSocket again automatically. We show the warning because there is no fail-safe for the events sent during the period when they were disconnected from webhooks. To ensure that the agents don't lose the updates during the disconnection, we encourage them to refresh the page using the warning. 

ref: https://github.com/chatwoot/chatwoot/issues/995

**Comment by sojan-official** [comment]
closing in favor of #995
