### ISSUE TITLE
WhatsApp 360Dialog - Not send messages

### ISSUE THREAD

**Issue by intelnexoec** [chatwoot/chatwoot#5207]
I identified a bug when I started the conversation in the contacts option and sent an approved template.
The template does reach the recipient but when you click, the conversation reaches chatwoot, chatwoot sends the autoresponder but never reaches the client. 

Attached screenshots

WhatsApp Template:

![image](https://user-images.githubusercontent.com/84194459/182997067-7836c40f-7d6d-4246-87bb-b21f1b5bffe1.png)

Chatwoot

![image](https://user-images.githubusercontent.com/84194459/182997186-cc001236-cda8-4cfd-b316-10d26444a64f.png)

Self-Hosted
V 2.6

**Comment by pranavrajs** [comment]
@sojan-official Is it similar to https://github.com/chatwoot/chatwoot/issues/5291?

**Comment by sojan-official** [comment]
@intelnexoec, is your auto responder configured via automation ?

Until the contract explicitly sends a message to your WhatsApp number.  Meta doesn't allow sending any other message content than approved templates. In your case, the content of the autoresponder you have configured doesn't match a valid template content. Since it was triggered before the incoming message from the user, it wasn't delivered on Whatsapp. 

----

Note: We can take this ticket to stop triggering such messages or give better visibility to the delivery status via https://github.com/chatwoot/chatwoot/issues/1021

--- 

Verified that system messages like a welcome message and CSAT is functioning correctly for 360 Dialog

<img width="1184" alt="Screenshot 2022-08-18 at 5 25 15 PM" src="https://user-images.githubusercontent.com/73185/185390366-1e1d8b8f-47e2-45f0-9e6f-c44eed3a4570.png">
<img width="1198" alt="Screenshot 2022-08-18 at 5 27 00 PM" src="https://user-images.githubusercontent.com/73185/185390382-5d76103d-66a3-4fb9-be8d-1c61c63bdd27.png">

cc: @pranavrajs

**Comment by intelnexoec** [comment]
@sojan-official OK you are right. She hadn't taken it into account. I activated the message from automation

**Comment by sojan-official** [comment]
Closing the issue as the investigation is completed
