### ISSUE TITLE
Tab Order in More Details Panel

### ISSUE THREAD

**Issue by kubre** [chatwoot/chatwoot#5364]
For only a single account Order in which tabs are shown is different. Like the previous conversation is last for everyone else but its the second one for a single account

Not even sure how to reproduce this cause it's only happening for a single account

**Expected behavior**

Order for tabs should be consitant

**Screenshots**

![image](https://user-images.githubusercontent.com/20380094/187842178-7780a679-4c95-4824-a719-895a5b075030.png)
![image](https://user-images.githubusercontent.com/20380094/187842194-432954eb-2a0d-484c-8583-0cb539589f34.png)

**Comment by kubre** [comment]
This is consistent no matter which Computer you open it on or what browser you use

**Comment by sojan-official** [comment]
@kubre  This is expected behavior. The sidebar panels can be reorganized via drag and drop. So the account owner should have reconfigured the positions. Feel free to reopen the issue if you find any other disparities. 

https://user-images.githubusercontent.com/73185/187901990-3cb79a18-f8b0-412a-881a-8e87335cd615.mov

**Comment by kubre** [comment]
I've never known this. Maybe the account has done it by mistake. Anyway thanks @sojan-official for your quick response
