### ISSUE TITLE
Issue with Integrate Whatsapp Cloud Api help

### ISSUE THREAD

**Issue by movilreup** [chatwoot/chatwoot#5447]
Hi people

I integrate Whatsapp cloud api in the portal but the chatwoot show error 
https://support.movilreup.com/webhooks/whatsapp/+14175516050

Error: {"error":"Error; wrong verify token"}

The token configuration is perfect. I send teste message from the meta developer and received in the portal but if is real message no received never in the portal.

any help me with this iddue?

![2022-09-17-12-42-developers facebook com](https://user-images.githubusercontent.com/96675665/190867455-3bd26aa4-9fd1-4bc1-acb7-525377d4da3e.png)

**Comment by guiqis** [comment]
When you directly click on the link, you'll see this error, because your browser is now sending the token.

Regarding the problem (message is sent only in the tests), check if you're using the same API version for development and tests inside facebook. There are a few versions that does not work with chatwoot. 

<img width="996" alt="image" src="https://user-images.githubusercontent.com/15745360/191869431-2a5508bb-3fa8-477f-813c-85410b0110f4.png">

Make sure that the same version (v13.0) is set in the "Test" and "Development" columns.

**Comment by movilreup** [comment]
if my number is approved.  I used it in the script (support board) and it worked perfectly.  the problem is when i do the configuration in chatwoot it stops working. my number and my business account is ready verify by meta. The problem only coming from change to chatwoot

**Comment by sojan-official** [comment]
@movilreup Chatwoot also required the user access token to have `manage_business` permissions. 
Check if the following URL is working with your access token.  ( replace business account id and access token )

"https://graph.facebook.com/v14.0/{business_account_id}/message_templates?access_token={access_token}"

**Comment by movilreup** [comment]
Yes i have user. Because I coming from Support Board script to chatwoot. And the number work support board but not in chatwoot and if send the receiving in the panel but real message not and i changed all webhook, token , webhook verify message.

And i create one account directly on chatwoot.com and test the number and work perfectly the problem is my self hosted 

![Screenshot_20220926-235715_Chrome](https://user-images.githubusercontent.com/96675665/192428831-5f5349d4-d679-4c03-af89-f7d97f0f74fb.png)

![Screenshot_20220926-235803_Chrome](https://user-images.githubusercontent.com/96675665/192428850-139d9c78-f817-4a4b-810a-dcaafdb14ac6.png)
