### ISSUE TITLE
Enable CSAT, Greetings Messages, Out of office message via API Channel

### ISSUE THREAD

**Issue by intelnexoec** [chatwoot/chatwoot#5514]
Please help us by enabling messages through the API.
Currently not receiving messages from:

*Welcome message
*CSAT
*Out of business hours

**Comment by grupale** [comment]
Hi @sojan-official ! Acording to this issue, in the API infox, if a conversatión is resolved and then re opened because an incoming message, the Greetings message, bussines hour and CSAT should be sended againg. I attatch and image as example of how it behaves now. Also the CSAT message should be translated acording to Account locale. Thanks

![image](https://user-images.githubusercontent.com/10934794/200849880-0fbf1acd-71b6-440d-b61c-c963c1c9a0df.png)

**Comment by grupale** [comment]
Hi @pranavrajs this is fixed in v2.11? Thanks

**Comment by robert0825** [comment]
@sojan-official is this fixed in v2.12?

**Comment by intelnexoec** [comment]
Hi @sojan-official is this fixed on the actual version? 2.13

**Comment by KarzounApps** [comment]
great to see this fixed in v2.14.0 :), I hope thigs goes okay

**Comment by sojan-official** [comment]
- Verified the CSAT and welcome messages will work in API Channel if enabled in your inbox settings.

**Comment by grupale** [comment]
Hi @sojan-official this is working in current version? Thanks

**Comment by sojan-official** [comment]
@grupale " if a conversatión is resolved and then re opened because an incoming message, the Greetings message, bussines hour and CSAT should be sended again. I attach and image as example of how it behaves now. Thanks!

This is a separate issue. ref: https://github.com/chatwoot/chatwoot/issues/4526#issuecomment-1132908401

lets track it over there.
