### ISSUE TITLE
feat: Ability to schedule message for later

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#5554]
Sometimes I would like to schedule my responses for a later time when it is more relevant to the contact.  It would be nice to have that ability in Chatwoot.

**Comment by amaljosea** [comment]
@sojan-official @pranavrajs @nithindavid 

**Use case:**
In my usecase my clients are in different timezones, so It would be great if I could schedule the message so that it goes in correct time when I am out of office.

**Some implementation ideas:**
1. Implement this feature in chatwoot core.
3. Implement as a plugin:
   -  See crisp for example:
      - https://crisp.chat/en/integrations/urn:beta.limited:message-scheduler:0/
      - https://crisp.chat/en/integrations/
    - Not sure if this is possible in chatwoot now. (A plugin which can modify the chatwoot UI, [see example](https://dev.to/boywithsilverwings/creating-a-json-crew-plugin-2l55))
4. Implement as a browser extensiton.
   -  Might not be the easiest/clever thing to do.

**Roadmap:**
Phase 1: Schedule text messages
Phase 2: Schedule audio, video and other kinds of messages.

Team, please suggest me a way to do this, I am intrested to work on this.

**Comment by pranavrajs** [comment]
Closing in favor of #9484
