### ISSUE TITLE
Unable to get email reply on Chatwoot of long thai texts

### ISSUE THREAD

**Issue by te-dious** [chatwoot/chatwoot#5565]
**Describe the bug**

Reply emails do not work as expected. Reply emails to some emails are not received in Chatwoot conversation thread.

**To Reproduce**

https://docs.google.com/document/d/1lIcFQ5R7X39H4dzBbYkV8cOhUv31Gax6rAkGOdCJP6A/edit

**Expected behavior**

The sent replies from emails are not received at Chatwoot.

**Comment by pranavrajs** [comment]
@te-dious Can you please update the document access to anyone with the link?

**Comment by te-dious** [comment]
Updated the access to Anyone with the link

**Comment by te-dious** [comment]
email thread content ->
[Gmail - ขออโลมพิจารณาปรับเบี้ยประกันภัยปีต่ออายุอีกครั้ง.pdf](https://github.com/chatwoot/chatwoot/files/9802453/Gmail.-.pdf)

**Comment by pranavrajs** [comment]
@tejaswinichile Adding this to the current sprint for priority.

**Comment by tejaswinichile** [comment]
@pranavrajs @te-dious I have checked the email export it's working fine.

Let me follow the steps mentioned above in the google doc with a different language.

@te-dious Can you send me the `original email/email export` for the `Acknowledged` reply that you mentioned here, in which you replied to the main email instead of translated email? 

https://docs.google.com/document/d/1lIcFQ5R7X39H4dzBbYkV8cOhUv31Gax6rAkGOdCJP6A/edit

**Comment by tejaswinichile** [comment]
I have followed the steps [here](https://docs.google.com/document/d/1lIcFQ5R7X39H4dzBbYkV8cOhUv31Gax6rAkGOdCJP6A/edit) and it's working fine with the long text and English/Thai replies. 

@te-dious Can you confirm, if you are still facing this issue?

**Comment by tejaswinichile** [comment]
@te-dious Can you please confirm, if you are still facing this issue?

If yes, would you be able to send the screencast video for the same?

**Comment by tejaswinichile** [comment]
We will reopen it if the client faces a similar issue or if we see it's reproducible on our cloud.
