### ISSUE TITLE
Display articles in the web widget

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5758]
TBD

**Comment by panaras10** [comment]
hey @pranavrajs  -- no offence but instead of planning and discussing new features, can you guys please focus on fixing the several bugs that were introduced with the latest updates?

**Comment by pranavrajs** [comment]
@panaras10 Can you please the bugs or issues you are facing? I can only see one of them reported here #5629 which is already in progress.

**Comment by iammattmartin** [comment]
I'd like to add a similar comment. Lots of focus being added for new features but still things like being able to continue conversations from the email sent is one. I get CW is trying to be all solutions to everyone but surely that is a core function otherwise if a guest comes to the site and goes, then changes computer, the conversation is lost with no way to resume via the site!

**Comment by panaras10** [comment]
Since 2.9.x we've had the following issues:

1) The chat timestamps are not updating correctly causing confusing across our agents
2) The chatbox has a weird bug where when you edit a message it adds a \n line
3) The websockets randomly shutdown showing "Chatwoot is Disconnected"
4) No Safari notifications?!?!

Thanks for the consideration. I understand that chatwoot needs to make money and maintain the business model but if you decide to release a product as open source, several considerations need to be made.

**Comment by iammattmartin** [comment]
I can confirm 1, 2 and 3 are replicated. We don't use Safari to confirm that.

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/7654. 

There are unrelated issues mentioned here. Please open them as separate issues if needed.
