### ISSUE TITLE
Show inbox name in conversation only if the account has more than one inbox

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#5843]
Currently, the inbox name is showing even though the account has only one inbox.

![Screenshot 2022-11-11 at 12 29 19 PM](https://user-images.githubusercontent.com/12408980/201285435-cfc41d4d-9d32-4e89-8ae4-7233886da399.png)

**Comment by glauberssoutodossantos** [comment]
I believe is better to collapse the inbox and labels bar. We we have one or two inboxes is not good the see that bar. It does not make any sense.

Look this issue here: https://github.com/chatwoot/chatwoot/issues/5360

![image](https://user-images.githubusercontent.com/99494469/202173670-2285fa37-78e7-4354-a9df-e8abf96a8f30.png)

**Comment by mariusa** [comment]
Thank you!
