### ISSUE TITLE
Bug: in V2.10.0 WhatsApp cloud api templates not syncing with chatwoot

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#5872]

**Comment by pranavrajs** [comment]
@voko3456 Can you please share a screencast or more about the behavior? Is it just some of the accounts or all of the accounts.

**Comment by jochenstu** [comment]
As I have had the same issue, I suspect this is the same UX problem: It does sync, but not immediately and, to me, it is still unclear when it does. Since there is no clear indicator that it should take any time at all, as a user I immediately start to wonder if it's just not working.

I am not sure how to handle this gracefully. Can the syncing frequency be increased, to the point where it's a none issue? Is this even within chatwoot control? Maybe addressing the issue in the documentation is the best course of action and good enough. I do think it would be neat to give the user more confidence.

**Comment by pranavrajs** [comment]
Closing this as the issue has been resolved in previous versions. (It was related to pagination of the templates.)
