### ISSUE TITLE
campaign doesn't send a message

### ISSUE THREAD

**Issue by sadden3194** [chatwoot/chatwoot#5979]
**Describe the bug**

Campaign doesn't work. No message will be sent.

**To Reproduce**

1. Create an Campaign via web interface like this:
![Bildschirm­foto 2022-11-29 um 11 21 29](https://user-images.githubusercontent.com/17011498/204503614-584e3b9d-ce95-42dd-a534-cd1171e477ef.png)
2. Open website, wait 2 seconds -> no message

**Environment**

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [X] Self-hosted
- - [ ] Linux VM
- - [X] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Comment by pranavrajs** [comment]
@Ghost108 Is there already an active conversation in the widget. If so, the campaigns would not be fired.

**Comment by Ghost108** [comment]
No there is no conversation active:
<img width="439" alt="Bildschirm­foto 2022-12-03 um 10 27 00" src="https://user-images.githubusercontent.com/17011498/205434073-3cab58a3-1660-4289-a20a-57d9bde6eacc.png">

but I get no message from campaign.
Get I no message because a bot is assigend to this inbox?

**Comment by Ghost108** [comment]
no support since 3 days :(

**Comment by sojan-official** [comment]
@sadden3194  Could you update to the latest version and try again? We haven't had any other reports on campaigns so far.  lets reopen this in case the issue persists.
