### ISSUE TITLE
Discarded Avatar::AvatarFromUrlJob due to a ActiveJob::DeserializationError.

### ISSUE THREAD

**Issue by Budfish** [chatwoot/chatwoot#6138]
**Describe the bug**

Send message to page from Facebook. It will receive message and Facebook contact name but not profile picture.
![image](https://user-images.githubusercontent.com/87319891/209806233-658355e3-89dd-4e5e-aa65-546a64a4f8b8.png)

**Expected behavior**

Showing the profile picture of the contact.
![image](https://user-images.githubusercontent.com/87319891/209806369-54d272bb-9819-4aef-88d8-f09458a176c3.png)

**Server logs**

E, [2022-12-28T09:10:09.878290 #359112] ERROR -- : Discarded Avatar::AvatarFromUrlJob due to a ActiveJob::DeserializationError.
2022-12-28T09:10:09.878Z pid=359112 tid=6pj0 class=Avatar::AvatarFromUrlJob jid=fe5e80723da6607a3a85c899 elapsed=0.005 INFO: done

**Environment**

self-hosted, Linux VM on Ubuntu 20.04,

**Cloud Provider** (If applicable)

GCP

**Comment by artdaniel306** [comment]
Update Server logs:

in worker log, there's one more error ActiveJob::DeserializationError:

E, [2022-12-28T21:44:14.311506 #566269] 
ERROR -- : Skipping job because of ActiveJob::DeserializationError (Error while trying to deserialize arguments: Couldn't find Contact with 'id'=43)

E, [2022-12-28T21:44:14.311649 #566269] 
ERROR -- : Discarded Avatar::AvatarFromUrlJob due to a ActiveJob::DeserializationError.

**Comment by tejaswinichile** [comment]
The contact has been deleted from the system, causing the issue, and the job is still running on the sidekiq-server.

It will be dead after three retries.
