### ISSUE TITLE
No Create WhatsApp channel 

### ISSUE THREAD

**Issue by movilreup** [chatwoot/chatwoot#6345]
Hello Support

No is possible save Whatsapp channel in version 2.13.0 after enter all details the app show no id possible save the channel.

**Comment by movilreup** [comment]
![213835647-a543dd7a-1809-4c0b-8d29-efffd7adf2f5](https://user-images.githubusercontent.com/96675665/214482301-7fbc8cf3-5167-460d-aae5-1eed01a97195.png)

**Comment by lexemekenya** [comment]
I am facing the same issue after upgrading to v2.13.0

**Comment by movilreup** [comment]
@lexemekenya variuos have the same problem after upgrade to version 2.13.0 

@sojan-official

**Comment by fealXX** [comment]
I also faced the same issue, but managed to create a inbox after some trying. 

The API Endpoint answers HTTP 422 with Response
`{"message":"Provider config Invalid Credentials","attributes":["provider_config"]}`

Check if you added the App to your System User as an Asset and AFTERWARDS (re-)created the access token. 
Otherwise it did not work for some reason. 

For debugging it helps to try to send messages through postman/curl like it is described in the first steps in the developer dashboard of your created meta-developer-app. Also, check for special characters in the beginning of the string, as facebook tends to add a tabspace onto the string when copying it from the "token created"-popup.
