### ISSUE TITLE
[CW-1587] Fetching last 10 emails only

### ISSUE THREAD

**Issue by sajangupta74** [chatwoot/chatwoot#6574]
**Describe the bug**

Currently the **fetch_imap_emails_job.rb** only fetch last 10 emails. So by any chance the process stopped and sync is stopped then after restarting the process it will only processes last 10 email and remaining emails will not be processed.

[Reference] Adding pr link below:
[#6498](https://github.com/chatwoot/chatwoot/pull/6498)

<sub>[CW-1587](https://linear.app/chatwoot/issue/CW-1587/fetching-last-10-emails-only)</sub>

**Comment by tejaswinichile** [comment]
@sajangupta74 Thanks 👍🏼 We will take this case into cosideration

**Comment by nickmonad** [comment]
Is it possible for the current behavior to be the default, while expanding the options for configuration to introduce a setting for the number of emails fetched? (For instance, if we know the process has been stopped for some time, say overnight due to a deployment issue, and we expect more than 10 emails have been received in that timeframe, the operator could redeploy with a setting to fetch a larger number of emails on the next sync)

Expanding the configuration options could also address this issue (https://github.com/chatwoot/chatwoot/pull/6498#issuecomment-1448612902), brought up by @pranavrajs 

If the operator could decide chatwoot should in fact only fetch unread emails (again, with the current behavior being the default as to not break existing expectations), that would be a big win for us in particular, when we know we don't use our email channels "out of band" from chatwoot. Everything in our setup is done through chatwoot anyway, for the inboxes we have configured. It would also fix this pressing issue we've experienced before with large attachments exceeding the daily Gmail IMAP bandwidth limit from time to time: https://github.com/chatwoot/chatwoot/issues/6082, as chatwoot fetches the same email over and over.

I think having those configuration options with documentation explaining the implication of enabling such behavior would be a fair tradeoff to make.

**Comment by tejaswinichile** [comment]
@nickmonad We, as a team, will discuss and update this issue with our approach. At first glance, we will provide the configuration to let the admin choose the number and type of emails to fetch. By default, it would be [10 emails - all emails]

**Comment by tejaswinichile** [comment]
We are scrapping fetching only the last email via IMAP with this [CW-1588](https://linear.app/chatwoot/issue/CW-1588/) fix. Now we will fetch the emails from yesterday, but as it should not clog the fetch imap email job, we are checking the dates last saved email and the current email dates. So with the current fix, we will have this one resolved.

**Comment by sojan-official** [comment]
* will be fixed in : https://github.com/chatwoot/chatwoot/issues/5081
