### ISSUE TITLE
[CW-1577] Reply Messages

### ISSUE THREAD

**Issue by digimaistecnologia** [chatwoot/chatwoot#6740]
Possibility of replying to a previously selected message. A simple "reply" option, in the 3 dots next to the message.

<sub>[CW-1577](https://linear.app/chatwoot/issue/CW-1577/reply-messages)</sub>

**Comment by iamsivin** [comment]
@digimaistecnologia Thanks for sharing. We will pick it up in the upcoming sprints.

**Comment by scmmishra** [comment]
@tejaswinichile and @iamsivin break this card down into sub-tasks

**Comment by pranavrajs** [comment]
@tejaswinichile @sojan-official Can We break it down before we can pick it up?

**Comment by nagorsky** [comment]
Need the same feature

**Comment by JJDROO** [comment]
waiting so long...

**Comment by nagorsky** [comment]
The biggest stop factor for us to move to chatwoot is no replies support.  I thought that this was not an important feature, but it turned out that our clients often use answers, and chatwoot does not show such messages at all.  so communication comes to a standstill and you have to ask again.  can this be fixed somehow?  maybe you can send at least a copy of it in the form of a private note instead of the quoted message?

**Comment by robert0825** [comment]
any update?
