### ISSUE TITLE
Sound notifications

### ISSUE THREAD

**Issue by whiteyhat** [chatwoot/chatwoot#703]
## Information
Is it possible to have sound alerts as well as email notifications? for real-time quick response, this will be highly beneficial

**Comment by pranavrajs** [comment]
@whiteyhat Autoplay sounds are blocked by most of the browsers, we had this discussion in the community before, instead of sounds we will be adding push notifications. 

The issue #681 in this sprint would cover this piece. 

Email notifications are already present, you can go to your profile screen and enable the email notifications you need.

**Comment by bfitec** [comment]
@pranavrajs I think audio alerts are crucial to the success of our team. We've found that if we take longer then 3 minutes to respond to a request the probability of closing a sales goes down 80%. We used Drift previously and the way they handled the autoplay issue was to request the user to click a button on a popup to enable audio notifications each time they log in. Generally browsers block audio notifications prior to user interaction.

**Comment by pranavrajs** [comment]
@bfitec Adding autoplay sounds which are blocked by browser seems to be a hacky fix for this. We want to do it right, we will be adding a notification centre and browser notifications in the release 1.4.0. Please see the issue #681

**Comment by whiteyhat** [comment]
@bfitec an alternative in the meantime is using a discord webhook. That worked for me

**Comment by bfitec** [comment]
@whiteyhat Yeah we're using Slack right now and it is working very well – while it works for initial notification it just isn't ideal for ongoing conversations. Our support team muted the support slack channel because of all the spam – which doesn't work long term. I think the push notifications may solve that.

**Comment by sojan-official** [comment]
We have merged audio alerts into the current develop branch. This should be available from v1.14.0

**Comment by head-dunce** [comment]
Is there a way to get a more annoying sound when a website chat comes in? It seems to just make a little click noise. My previous chat would make a doorbell ringing sound over and over until I ran back to the computer and interacted with the person. I'm often doing things around the office and won't hear that little click.

**Comment by sojan-official** [comment]
@head-dunce  tracking this over : https://github.com/chatwoot/chatwoot/issues/2983
