### ISSUE TITLE
Is it not more possible to install previous versions?

### ISSUE THREAD

**Issue by yelsew00** [chatwoot/chatwoot#7211]
### Describe the bug

I'm trying to install version 2.16.1 on google cloud, oracle and locaweb (Brazilian vps service)
and it doesn't work, I changed the parameter in the install.sh file from "$BRANCH" to "7bd4007" and in ubuntu 20 and 22 the same error happens.
checking the installation log file I came across the following record:

`Required ruby-3.1.3 is not installed.
To install do: 'rvm install "ruby-3.1.3"'
HEAD is now at 18c5c4783 Merge branch 'hotfix/2.16.1'
Your Ruby version is 3.2.2, but your Gemfile specified 3.1.3
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed
Done in 1.16s.
rake aborted!
Bundler::RubyVersionMismatch: Your Ruby version is 3.2.2, but your Gemfile specified 3.1.3
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.3.26/lib/bundler/definition.rb:432:in `validate_ruby!'
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.3.26/lib/bundler/definition.rb:407:in `validate_runti>
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.3.26/lib/bundler.rb:155:in `setup'
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.3.26/lib/bundler/setup.rb:20:in `block in <top (requi>
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.3.26/lib/bundler/ui/shell.rb:136:in `with_level'
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.3.26/lib/bundler/ui/shell.rb:88:in `silence'
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.3.26/lib/bundler/setup.rb:20:in `<top (required)>'
<internal:/usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:i>
<internal:/usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:i>
/home/chatwoot/chatwoot/config/boot.rb:3:in `<top (required)>'
/home/chatwoot/chatwoot/config/application.rb:3:in `require_relative'
/home/chatwoot/chatwoot/config/application.rb:3:in `<top (required)>'
/home/chatwoot/chatwoot/Rakefile:4:in `require_relative'
/home/chatwoot/chatwoot/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)`

### To Reproduce

1- wget install.sh file
2-change the parameter "$BRANCH" to "7bd4007" in the file
3- ./install.sh --install

### Expected behavior

that the installation is completed

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

ubuntu 22 lts and ubuntu 20 lts

### Additional context

im trying in google cloud, oracle cloud and locaweb "brazilian service"

**Comment by vishnu-narayanan** [comment]
@yelsew00 It is possible to install older versions, but we recommend always installing the latest release version.

The issue you are facing with installing an older version is due to the Ruby upgrade as part of the 2.17 release. If you want to try out the older version. The easiest way would be to use the docker deployment. You can switch the image tag to whichever version of Chatwoot you want. 

Ref:https://www.chatwoot.com/docs/self-hosted/deployment/docker

If you still want to use the Linux installation, change lines 334 and 335 in the installer script to
```
rvm install "ruby-3.1.3"
rvm use 3.1.3 --default
```

And run

```
./install.sh -I 7bd4007
```
Ref: https://github.com/chatwoot/chatwoot/blob/412d750b6a2dfbccbfffe18e25434bfafeb3f362/deployment/setup_20.04.sh#L334
