### ISSUE TITLE
telegram inbox send to agent bot even not pending

### ISSUE THREAD

**Issue by bosaeed** [chatwoot/chatwoot#7340]
### Describe the bug

if inbox connected to telegram channel in  it start in pending status but after change status to open by calling api or by click open button still send every message to agent bot

### To Reproduce

1. create telegram inbox
2. connect to agent bot as in rasa demo
3. change conversion status to open
4. rasa still receive messages

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by sojan-official** [comment]
@bosaeed This is expected behaviour since we envisioned agent bots to chip in even when agents' responses are delayed in open conversations.  You can look at the status of the conversation in the incoming payload and decide whether to respond to the message or not inside your logic for the agent bot.
