### ISSUE TITLE
Error when uploading avatar Linux install.

### ISSUE THREAD

**Issue by efrancou** [chatwoot/chatwoot#7390]
### Describe the bug

When uploading an avantar then it shows error 500 on loading image:
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

https://github.com/chatwoot/chatwoot/assets/6466600/b06110f1-f7f7-4fc0-91ea-6581ffcb7ea5

### To Reproduce

Linux Install
Local storage
Upload user avatar (only tested with superadmin)
It happens with PNG/JPG.
When reloading avatar is missing, inspector shows error on loading.

### Expected behavior

Load image avatar

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu

### Browser and version

Chrome lastest

### Additional context

Hosted on Hetzner (ARM)

**Comment by pranavrajs** [comment]
@efrancou This happens due to the usage of disk storage. The behavior is different in different providers. Please use a cloud storage as per the guide [here](https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers). Feel free to re-open the issue if it still persists after setting up the cloud storage.

**Comment by efrancou** [comment]
# Storage
ACTIVE_STORAGE_SERVICE=s3_compatible
STORAGE_BUCKET_NAME=bucket-chat-cdn
STORAGE_ACCESS_KEY_ID=XXXXXXX
STORAGE_SECRET_ACCESS_KEY=XXXXXXX
STORAGE_REGION=nyc3
STORAGE_ENDPOINT=https://nyc3.digitaloceanspaces.com

DIRECT_UPLOADS_ENABLED=true

**Comment by efrancou** [comment]
Images are uploading OK to Spaces BUT not displayed inside Chatwoot
