### ISSUE TITLE
New created contact is disappeared

### ISSUE THREAD

**Issue by Edik-Apoyan** [chatwoot/chatwoot#7430]
### Describe the bug

When a user creates a contact only with a name, it is created properly, but after refreshing the page, the created contact has disappeared.

### To Reproduce

1. Open the Admin account
2. Navigate to the Contact page
3. Create a new contact only with name
4. Refresh the page

### Expected behavior

If for creating a new contact email field is mandatory for saving the contact, The Admin user shouldn't be able to create a contact only with name

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by karthi07** [comment]
the contacts created without email ids are saved in the database, but they aren't displayed on the frontend due to various reasons.

the backend the contacts are indexed based on the following condition, which is preventing the customers without email ids being displayed.

#  index_contacts_on_nonempty_fields                     (account_id,email,phone_number,identifier) WHERE (((email)::text <> ''::text) OR ((phone_number)::text <> ''::text) OR ((identifier)::text <> ''::text))

@team what should be the right functionality here?

1. display the contacts if the email id is null
2. prevent users from adding contacts without email id 
 

![image](https://github.com/chatwoot/chatwoot/assets/5237154/fffef1b9-724a-46eb-826f-f5b3ba64284c)

**Comment by sojan-official** [comment]
Chatwoot displays only the resolved contacts, ie the ones which can be contacted back in the CRM tab. 
These are the contacts which have identifiable information like email/phone/identifier. 

@karthi07 the current behaviour should be okay for now. 

display the contacts if the email id is null
- not much value add in showing such contacts if don't have a way to identify them 

prevent users from adding contacts without email id
- We don't want to prevent this since the an unidentified contact could turn into identified in future when they provide us the email. example : live Chat
