### ISSUE TITLE
[CW-2264] feat:  Add `toggle_typing` endpoint for client APIs

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#7581]
### Is your feature or enhancement related to a problem? Please describe.

>  I’ve starting implementing our own live chat frontend using the client APIs + websocket. One thing that’s not clear is whether or not we can communicate when our user (Contact) is typing with the the chatwoot agent (User). I’ve tried sending the conversation.typing_on and conversation.typing_off messages from our site to the chatwoot websocket channel but I’m not seeing anything in the dashboard. Is it possible to achieve this functionality?

ref: https://app.chatwoot.com/app/accounts/1/conversations/26104

### Describe the solution you'd like

implement `toggle_typing` endpoint to conversation public APIs

ref: https://github.com/chatwoot/chatwoot/blob/develop/app/controllers/public/api/v1/inboxes/conversations_controller.rb

ref: https://github.com/chatwoot/chatwoot/blob/30f39289042c40a4dfeab5ed50f6e53b5cab17d4/app/controllers/api/v1/widget/conversations_controller.rb#L43

<sub>[CW-2264](https://linear.app/chatwoot/issue/CW-2264/feat-add-toggle-typing-endpoint-for-client-apis)</sub>

**Comment by camin-mccluskey** [comment]
Thanks for putting this feature on your backlog, it would be fantastically helpful to help build client facing apps using Chatwoot as a chat backend. 

I was wondering if there is any reason we need to issue commands to the client API rather than as messages to the Websocket channel where we receive events? Currently we are limited to sending `subscribe` and `update_presence` messages to the Websocket, why not also send `create.message` and `conversation.typing_on`/`conversation.typing_off` messages also? This feels like a cleaner pattern for interactions, post creating a contact/conversation with the Client APIs.

**Comment by sojan-official** [comment]
@camin-mccluskey The way the APIs are designed so far is that all the CRUD actions happen via HTTP APIs. The websockets are for delivering real-time updates to clients alone.  

It's just that it was the initial implementation we opted for, and then it became the standard. We will go ahead and revisit this at a later point.

**Comment by camin-mccluskey** [comment]
@sojan-official Thanks for actioning so quickly. I'm looking into implementing this on our side now. Is this feature fully released and, if so, is there documentation for it?
