### ISSUE TITLE
Twitter / X Missing

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#7666]
### Is your feature or enhancement related to a problem? Please describe.

Latest dev, Twitter (X)is missing to be added.

I can see a commit for this being removed but why? The API still works and can be used, especially for those that may want to pay for higher query amounts.

We still use this and it still works just fine.

### Describe the solution you'd like

Re-add ability to add accounts.

**Comment by pranavrajs** [comment]
@iammattmartin We will not be picking this up. https://github.com/orgs/chatwoot/discussions/6983

To use the Account Activity API, you need to have the enterprise edition since it is not available in the $100 plan. As far as we know, the API charges are $42k per month. If the integration works on your account, that's good and to be honest, surprising. However, for the community, there is no point in maintaining this unless something changes drastically.

**Comment by iammattmartin** [comment]
The $100 option allows you to use the Timelines option, or even Mentions, which you can then find tweets aimed at your username and then reply to them. Why is this not going to be supported when the features on the cheap API option seems possible??

**Comment by pranavrajs** [comment]
@iammattmartin [This API](https://developer.twitter.com/en/docs/twitter-api/enterprise/account-activity-api/overview) is what we use. It's not available in the free or $100 paid plan.

**Comment by iammattmartin** [comment]
OK so instead of using that, why can you not use the features in the $100 tier which can search for tweets aimed at an account usenrame (which you'd already know) and then tweet out accordingly.

This would work and still mean that this can be used as a channel instead of writing it off completely....

Specifically: https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/introduction, https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/introduction and/or https://developer.twitter.com/en/docs/twitter-api/tweets/search/introduction.
