### ISSUE TITLE
Contributing guide - Docker Setup

### ISSUE THREAD

**Issue by sergbbb** [chatwoot/chatwoot#7842]
### Describe the bug

Error on **docker compose build**

```
=> ERROR [webpack internal] load metadata for docker.io/library/chatwoot:development

failed to solve: chatwoot:development: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

### To Reproduce

git clone https://github.com/chatwoot/chatwoot.git

cp .env.example .env # update redis and postgres passwords
nano .env #update docker-compose.yml with the same postgres password
nano docker-compose.yml

docker-compose build

### Expected behavior

No errors =)

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Operating system

Windows 11

### Docker (if applicable)

Docker version 24.0.5, build ced0996
Docker Compose version v2.20.2-desktop.1

**Comment by sergbbb** [comment]
Solved with `docker-compose build base` before docker-compose build

I think can be fixed with depends on base in all images in docker-compose file

**Comment by Cheizr** [comment]
After using docker-compose build base i was getting this output, the fix is:

git add .
git commit -m "init"

``ERROR [base pre-builder 13/14] RUN git rev-parse HEAD > /app/.git_sha                                                                                                                    0.6s 
------
[base pre-builder 13/14] RUN git rev-parse HEAD > /app/.git_sha:
0.620 fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
0.620 Use '--' to separate paths from revisions, like this:
0.620 'git <command> [<revision>...] -- [<file>...]'
------
failed to solve: process "/bin/sh -c git rev-parse HEAD > /app/.git_sha" did not complete successfully: exit code: 128``

**Comment by sergbbb** [comment]
@Cheizr Now another issues on `docker compose up`:

```
chatwoot-webpack-1   | exec docker/entrypoints/webpack.sh: no such file or directory

chatwoot-rails-1   | exec docker/entrypoints/rails.sh: no such file or directory
```

**Comment by sergbbb** [comment]
Resolved: On Windows EOL should be LF
