### ISSUE TITLE
[CW-2457] fix: Make activity timestamp messages translatable

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#7862]
![image.png](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/529c075a-7850-4329-bb29-1f3c7a813efc/9f1fbf44-b06c-4fa5-ba9b-a477ed22b76b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi81MjljMDc1YS03ODUwLTQzMjktYmIyOS0xZjNjN2E4MTNlZmMvOWYxZmJmNDQtYjA2Yy00ZmE1LWJhOWItYTQ3N2VkMjJiNzZiIiwiaWF0IjoxNjkzOTUwNDA4LCJleHAiOjE2OTQwMzY4MDh9.gBZSnonfZSz1MFx5s9W_l4PrpdKp5GEH5GFMTC0o5Ac)

These copies aren't translatable at the moment. 

ref: [https://github.com/chatwoot/chatwoot/blob/9322112481e6341b6b291d7d44b234434a2f6c9b/app/javascript/dashboard/components/ui/TimeAgo.vue#L56](https://github.com/chatwoot/chatwoot/blob/9322112481e6341b6b291d7d44b234434a2f6c9b/app/javascript/dashboard/components/ui/TimeAgo.vue#L56)

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2457](https://linear.app/chatwoot/issue/CW-2457/fix-make-activity-timestamp-messages-translatable)</sub>

**Comment by jsobralgitpush** [comment]
Can i work on this issue?

**Comment by sojan-official** [comment]
@jsobralgitpush  please go ahead

**Comment by jsobralgitpush** [comment]
I would like to know if i’m in the right way to solve the issue. I’m intending to do the following

1. Since the `TimeAgo.vue` is called in `conversation/ConversationCard.vue`, i’m presuming that `TimeAgo` is part of `conversation` module
2. Because of it, i’ll search for the string i want to translate in the properly translation file, which is `conversation.json`  since point 1. 
3. At `conversation.json`, we do not have the translation for the strings we want
    1. `Created`
    2. `Created at`
    3. `Last activity`
4. So, the job is to insert these 3 translations in the 39  `conversation.json` files, one for each language

Am i in the right way?

Some additional questions:

- `TimeAgo.vue` is called only inside `ConversationCard.vue` , but  `ConversationCard.vue` is called inside `ChatList.vue` and on `ContactConversation.vue` . In the `ChatList.vue` , we already use some translations from the `chatlist.json` file. In that file, we already have a translation for `CREATED_AT` . Should i already use this translation instead of add it on `conversation.vue`?
- In did not found in the code but where `this.$t` is defined to be available in every file?

It is a pleasure to be here, thanks!

**Comment by iamsivin** [comment]
> I would like to know if i’m in the right way to solve the issue. I’m intending to do the following
> 
> 1. Since the `TimeAgo.vue` is called in `conversation/ConversationCard.vue`, i’m presuming that `TimeAgo` is part of `conversation` module
> 2. Because of it, i’ll search for the string i want to translate in the properly translation file, which is `conversation.json`  since point 1.
> 3. At `conversation.json`, we do not have the translation for the strings we want
>    
>    1. `Created`
>    2. `Created at`
>    3. `Last activity`
> 4. So, the job is to insert these 3 translations in the 39  `conversation.json` files, one for each language
> 
> Am i in the right way?
> 
> Some additional questions:
> 
> * `TimeAgo.vue` is called only inside `ConversationCard.vue` , but  `ConversationCard.vue` is called inside `ChatList.vue` and on `ContactConversation.vue` . In the `ChatList.vue` , we already use some translations from the `chatlist.json` file. In that file, we already have a translation for `CREATED_AT` . Should i already use this translation instead of add it on `conversation.vue`?
> * In did not found in the code but where `this.$t` is defined to be available in every file?
> 
> It is a pleasure to be here, thanks!

@jsobralgitpush Hey, you can add it in this file `app/javascript/dashboard/i18n/locale/en/chatlist.json`. Like
```
    "CHAT_TIME_STAMP": {
      "CREATED": {
        "LATEST": "Created",
        "OLDEST": "Created at:"
      },
      "LAST_ACTIVITY": {
        "NOT_ACTIVE": "Last activity :",
        "ACTIVE": "Last activity"
      }
    },
```
And use it in the TimeAgo component ``${this.$t('CHAT_LIST.CHAT_TIME_STAMP.CREATED.LATEST')} ${
            this.createdAtTimeAgo
          }``

**Comment by jsobralgitpush** [comment]
![image](https://github.com/chatwoot/chatwoot/assets/63429525/d4398e9e-2984-4d25-bcb8-c0b6565c7cc3)

Hello, guys!

I've open the PR for this issue today, but one workflow failed. It was something related to eslint style in a part of the codebase that i did not touch. Should i fix it?

**Comment by iamsivin** [comment]
> ![image](https://user-images.githubusercontent.com/63429525/269447520-d4398e9e-2984-4d25-bcb8-c0b6565c7cc3.png)
> 
> Hello, guys!
> 
> I've open the PR for this issue today, but one workflow failed. It was something related to eslint style in a part of the codebase that i did not touch. Should i fix it?

@jsobralgitpush Yes. You can fix the `TimeAgo.vue` component issue. There is a Prettier format problem.

**Comment by grupale** [comment]
Hi @iamsivin @sojan-official I've checked this issue in 3.2 version. Now the titles of Created and Last activity are translated but not the date values in it. 
![image](https://github.com/chatwoot/chatwoot/assets/10934794/c260156c-46bd-46f9-bc7c-0655f83d44cc)
