### ISSUE TITLE
#SMTP doesn't work after setting up env config. with V3.0.0

### ISSUE THREAD

**Issue by mthakur5** [chatwoot/chatwoot#7869]
### Describe the bug

Mail::Sendmail::DeliveryError: Delivery failed with exitstatus 1: "/usr/sbin/sendmail -i -f \"accounts@chatwoot.com\" -- \"myemail@email.com\""

i have followed every steps : https://www.chatwoot.com/docs/product/channels/email/configure-smtp/ and, Run cammand:Account.find(1).support_email. 

outcome is good. 
<img width="719" alt="Screenshot 2023-09-06 at 10 04 29 PM" src="https://github.com/chatwoot/chatwoot/assets/138131563/3c886da9-0536-48e7-8013-f901dd7dfa4c">

i am using aws ses. someone help me?

### To Reproduce

MAILER_SENDER_EMAIL=myemail@email.com
SMTP_ADDRESS=email-smtp.ap-west-1.amazonaws.com
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_USERNAME=AKIAWQRGY87VFB7RAQWE
SMTP_PASSWORD=kjndjnB897lmxgWc49TTJYcKsyNcmC62yaue

### Environment

Docker

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Linux

### Docker (if applicable)

Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:23 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:23 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by pranavrajs** [comment]
@mthakur5 Thanks for the details. However, this doesn't seem to be an issue with Chatwoot. Please share the complete logs  to debug this further.

**Comment by iyadahmed** [comment]
I still have this issue :/ pls help

**Comment by iyadahmed** [comment]
the logs don't contain anything about SMTP :/
docker compose logs -f

**Comment by mredodos** [comment]
same issue

**Comment by mredodos** [comment]
Mail::Sendmail::DeliveryError: Delivery failed with exitstatus 1: "/usr/sbin/sendmail -i -f \"accounts@chatwoot.com\"

**Comment by mredodos** [comment]
is like chatwoot had config.action_mailer.delivery_method = :sendmail instead of :smtp

**Comment by pranavrajs** [comment]
@ssh-sato Can you please post the complete env file? This issue is not reproducible at our end with the usual config. I believe this has to do something with the config.

**Comment by ssh-sato** [comment]
@pranavrajs sure, it's weird because the same config working fine in v2


# Used to verify the integrity of signed cookies. so ensure a secure value is set
SECRET_KEY_BASE=************
ENABLE_RACK_ATTACK = false
# Replace with the URL you are planning to use for your app
FRONTEND_URL=http://localhost:3000
# To use a dedicated URL for help center pages
# HELPCENTER_URL=http://localhost:3000

# If the variable is set, all non-authenticated pages would fallback to the default locale.
# Whenever a new account is created, the default language will be DEFAULT_LOCALE instead of en
# DEFAULT_LOCALE=en

# If you plan to use CDN for your assets, set Asset CDN Host
ASSET_CDN_HOST=

# Force all access to the app over SSL, default is set to false
FORCE_SSL=false

# This lets you control new sign ups on your convergence installation
# true : default option, allows sign ups
# false : disables all the end points related to sign ups
# api_only: disables the UI for signup, but you can create sign ups via the account apis
ENABLE_ACCOUNT_SIGNUP=false

# Redis config
REDIS_URL=redis://localhost:6379
# If you are using docker-compose, set this variable's value to be any string,
# which will be the password for the redis service running inside the docker-compose
# to make it secure
REDIS_PASSWORD=
# Redis Sentinel can be used by passing list of sentinel host and ports e,g. sentinel_host1:port1,sentinel_host2:port2
REDIS_SENTINELS=
# Redis sentinel master name is required when using sentinel, default value is "mymaster".
# You can find list of master using "SENTINEL masters" command
REDIS_SENTINEL_MASTER_NAME=

# By default convergence will pass REDIS_PASSWORD as the password value for sentinels
# Use the following environment variable to customize passwords for sentinels.
# Use empty string if sentinels are configured with out passwords
# REDIS_SENTINEL_PASSWORD=

# Redis premium breakage in heroku fix
# enable the following configuration
# REDIS_OPENSSL_VERIFY_MODE=none_

# Postgres Database config variables
# You can leave POSTGRES_DATABASE blank. The default name of
# the database in the production environment is convergence_production
# POSTGRES_DATABASE=
POSTGRES_HOST=localhost
POSTGRES_USERNAME=*******
POSTGRES_PASSWORD=********
RAILS_ENV=production
# Changes the Postgres query timeout limit. The default is 14 seconds. Modify only when required.
# POSTGRES_STATEMENT_TIMEOUT=14s
RAILS_MAX_THREADS=5

# The email from which all outgoing emails are sent
# could user either  `email@yourdomain.com` or `BrandName <email@yourdomain.com>`
MAILER_SENDER_EMAIL=******** <*********@******.net>

#SMTP domain key is set up for HELO checking
SMTP_DOMAIN=smtp.mailgun.org
# Set the value to "mailhog" if using docker-compose for development environments,
# Set the value as "localhost" or your SMTP address in other environments
# If SMTP_ADDRESS is empty, convergence would try to use sendmail(postfix)
SMTP_ADDRESS=smtp.mailgun.org
SMTP_PORT=587
SMTP_USERNAME=*********@******.net
SMTP_PASSWORD=*********************
# plain,login,cram_md5
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
# Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert', see http://api.rubyonrails.org/classes/ActionMailer/Base.html
SMTP_OPENSSL_VERIFY_MODE=none
# Comment out the following environment variables if required by your SMTP server
SMTP_TLS=false
SMTP_SSL=false

# Mail Incoming
# This is the domain set for the reply emails when conversation continuity is enabled
MAILER_INBOUND_EMAIL_DOMAIN=
# Set this to appropriate ingress channel with regards to incoming emails
# Possible values are :
# relay for Exim, Postfix, Qmail
# mailgun for Mailgun
# mandrill for Mandrill
# postmark for Postmark
# sendgrid for Sendgrid
RAILS_INBOUND_EMAIL_SERVICE=
# Use one of the following based on the email ingress service
# Ref: https://edgeguides.rubyonrails.org/action_mailbox_basics.html
RAILS_INBOUND_EMAIL_PASSWORD=
MAILGUN_INGRESS_SIGNING_KEY=
MANDRILL_INGRESS_API_KEY=

# Storage
ACTIVE_STORAGE_SERVICE=local

# Amazon S3
S3_BUCKET_NAME=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=

# Log settings
# Disable if you want to write logs to a file
RAILS_LOG_TO_STDOUT=true
LOG_LEVEL=info
LOG_SIZE=500

### This environment variables are only required if you are setting up social media channels

# Facebook
FB_VERIFY_TOKEN=********
FB_APP_SECRET=***************
FB_APP_ID=****************

# https://developers.facebook.com/docs/messenger-platform/instagram/get-started#app-dashboard
IG_VERIFY_TOKEN=

# Twitter
TWITTER_APP_ID=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_ENVIRONMENT=

#slack integration
SLACK_CLIENT_ID=
SLACK_CLIENT_SECRET=

# Google OAuth
GOOGLE_OAUTH_CLIENT_ID=
GOOGLE_OAUTH_CLIENT_SECRET=
GOOGLE_OAUTH_CALLBACK_URL=

### Change this env variable only if you are using a custom build mobile app
## Mobile app env variables
IOS_APP_ID=
ANDROID_BUNDLE_ID=

# https://developers.google.com/android/guides/client-auth (use keytool to print the fingerprint in the first section)
ANDROID_SHA256_CERT_FINGERPRINT=AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8

### Smart App Banner
# https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html
# You can find your app-id in https://itunesconnect.apple.com
#IOS_APP_IDENTIFIER=1495796682

## Push Notification
## generate a new key value here : https://d3v.one/vapid-key-generator/
# VAPID_PUBLIC_KEY=
# VAPID_PRIVATE_KEY=
#
# for mobile apps
# FCM_SERVER_KEY=

### APM and Error Monitoring configurations
## Elastic APM
## https://www.elastic.co/guide/en/apm/agent/ruby/current/getting-started-rails.html
# ELASTIC_APM_SERVER_URL=
# ELASTIC_APM_SECRET_TOKEN=

## Sentry
# SENTRY_DSN=

## LogRocket
# LOG_ROCKET_PROJECT_ID=xxxxx/some-project

## Scout
## https://scoutapm.com/docs/ruby/configuration
# SCOUT_KEY=YOURKEY
# SCOUT_NAME=YOURAPPNAME (Production)
# SCOUT_MONITOR=true

## NewRelic
# https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration/
# NEW_RELIC_LICENSE_KEY=
# Set this to true to allow newrelic apm to send logs.
# This is turned off by default.
# NEW_RELIC_APPLICATION_LOGGING_ENABLED=

## Datadog
## https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#environment-variables
# DD_TRACE_AGENT_URL=

# MaxMindDB API key to download GeoLite2 City database
# IP_LOOKUP_API_KEY=

## Rack Attack configuration
## To prevent and throttle abusive requests
# ENABLE_RACK_ATTACK=true

## Running convergence as an API only server
## setting this value to true will disable the frontend dashboard endpoints
# CW_API_ONLY_SERVER=false

## Development Only Config
# if you want to use letter_opener for local emails
# LETTER_OPENER=true
# meant to be used in github codespaces
# WEBPACKER_DEV_SERVER_PUBLIC=

# If you want to use official mobile app,
# the notifications would be relayed via a convergence server
ENABLE_PUSH_RELAY_SERVER=true

# Stripe API key
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=

# Set to true if you want to upload files to cloud storage using the signed url
# Make sure to follow https://edgeguides.rubyonrails.org/active_storage_overview.html#cross-origin-resource-sharing-cors-configuration on the cloud storage after setting this to true.
DIRECT_UPLOADS_ENABLED=

#MS OAUTH creds
AZURE_APP_ID=
AZURE_APP_SECRET=

## Advanced configurations
## Change these values to fine tune performance
# control the concurrency setting of sidekiq
# SIDEKIQ_CONCURRENCY=10

INSTALLATION_ENV=linux_script

**Comment by ssh-sato** [comment]
sure @pranavrajs, it's weird because it works on v2 with the same config
.env:

# Used to verify the integrity of signed cookies. so ensure a secure value is set
SECRET_KEY_BASE=oJhnNoj6McoNYgaxoLnIAh1LuHbnNYFbLB3mLGRFSPnoZpTO3f0RguYUUBwvxXs
ENABLE_RACK_ATTACK = false
# Replace with the URL you are planning to use for your app
FRONTEND_URL=http://localhost:3000
# To use a dedicated URL for help center pages
# HELPCENTER_URL=http://localhost:3000

# If the variable is set, all non-authenticated pages would fallback to the default locale.
# Whenever a new account is created, the default language will be DEFAULT_LOCALE instead of en
# DEFAULT_LOCALE=en

# If you plan to use CDN for your assets, set Asset CDN Host
ASSET_CDN_HOST=

# Force all access to the app over SSL, default is set to false
FORCE_SSL=false

# This lets you control new sign ups on your chatwoot installation
# true : default option, allows sign ups
# false : disables all the end points related to sign ups
# api_only: disables the UI for signup, but you can create sign ups via the account apis
ENABLE_ACCOUNT_SIGNUP=false

# Redis config
REDIS_URL=redis://localhost:6379
# If you are using docker-compose, set this variable's value to be any string,
# which will be the password for the redis service running inside the docker-compose
# to make it secure
REDIS_PASSWORD=
# Redis Sentinel can be used by passing list of sentinel host and ports e,g. sentinel_host1:port1,sentinel_host2:port2
REDIS_SENTINELS=
# Redis sentinel master name is required when using sentinel, default value is "mymaster".
# You can find list of master using "SENTINEL masters" command
REDIS_SENTINEL_MASTER_NAME=

# By default chatwoot will pass REDIS_PASSWORD as the password value for sentinels
# Use the following environment variable to customize passwords for sentinels.
# Use empty string if sentinels are configured with out passwords
# REDIS_SENTINEL_PASSWORD=

# Redis premium breakage in heroku fix
# enable the following configuration
# REDIS_OPENSSL_VERIFY_MODE=none_

# Postgres Database config variables
# You can leave POSTGRES_DATABASE blank. The default name of
# the database in the production environment is chatwoot_production
# POSTGRES_DATABASE=
POSTGRES_HOST=localhost
POSTGRES_USERNAME=chatwoot
POSTGRES_PASSWORD=Sjqipdis0Ye32EM
RAILS_ENV=production
# Changes the Postgres query timeout limit. The default is 14 seconds. Modify only when required.
# POSTGRES_STATEMENT_TIMEOUT=14s
RAILS_MAX_THREADS=5

# The email from which all outgoing emails are sent
# could user either  `email@yourdomain.com` or `BrandName <email@yourdomain.com>`
MAILER_SENDER_EMAIL=***** <********@*******.net>

#SMTP domain key is set up for HELO checking
SMTP_DOMAIN=smtp.mailgun.org
# Set the value to "mailhog" if using docker-compose for development environments,
# Set the value as "localhost" or your SMTP address in other environments
# If SMTP_ADDRESS is empty, chatwoot would try to use sendmail(postfix)
SMTP_ADDRESS=smtp.mailgun.org
SMTP_PORT=587
SMTP_USERNAME=**********@********.net
SMTP_PASSWORD=***********************
# plain,login,cram_md5
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
# Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert', see http://api.rubyonrails.org/classes/ActionMailer/Base.html
SMTP_OPENSSL_VERIFY_MODE=none
# Comment out the following environment variables if required by your SMTP server
SMTP_TLS=false
SMTP_SSL=false

# Mail Incoming
# This is the domain set for the reply emails when conversation continuity is enabled
MAILER_INBOUND_EMAIL_DOMAIN=
# Set this to appropriate ingress channel with regards to incoming emails
# Possible values are :
# relay for Exim, Postfix, Qmail
# mailgun for Mailgun
# mandrill for Mandrill
# postmark for Postmark
# sendgrid for Sendgrid
RAILS_INBOUND_EMAIL_SERVICE=
# Use one of the following based on the email ingress service
# Ref: https://edgeguides.rubyonrails.org/action_mailbox_basics.html
RAILS_INBOUND_EMAIL_PASSWORD=
MAILGUN_INGRESS_SIGNING_KEY=
MANDRILL_INGRESS_API_KEY=

# Storage
ACTIVE_STORAGE_SERVICE=local

# Amazon S3
S3_BUCKET_NAME=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=

# Log settings
# Disable if you want to write logs to a file
RAILS_LOG_TO_STDOUT=true
LOG_LEVEL=info
LOG_SIZE=500

### This environment variables are only required if you are setting up social media channels

# Facebook
FB_VERIFY_TOKEN=************
FB_APP_SECRET=****************
FB_APP_ID=************

# https://developers.facebook.com/docs/messenger-platform/instagram/get-started#app-dashboard
IG_VERIFY_TOKEN=

# Twitter
TWITTER_APP_ID=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_ENVIRONMENT=

#slack integration
SLACK_CLIENT_ID=
SLACK_CLIENT_SECRET=

# Google OAuth
GOOGLE_OAUTH_CLIENT_ID=
GOOGLE_OAUTH_CLIENT_SECRET=
GOOGLE_OAUTH_CALLBACK_URL=

### Change this env variable only if you are using a custom build mobile app
## Mobile app env variables
IOS_APP_ID=
ANDROID_BUNDLE_ID=

# https://developers.google.com/android/guides/client-auth (use keytool to print the fingerprint in the first section)
ANDROID_SHA256_CERT_FINGERPRINT=AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8

### Smart App Banner
# https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html
# You can find your app-id in https://itunesconnect.apple.com
#IOS_APP_IDENTIFIER=1495796682

## Push Notification
## generate a new key value here : https://d3v.one/vapid-key-generator/
# VAPID_PUBLIC_KEY=
# VAPID_PRIVATE_KEY=
#
# for mobile apps
# FCM_SERVER_KEY=

### APM and Error Monitoring configurations
## Elastic APM
## https://www.elastic.co/guide/en/apm/agent/ruby/current/getting-started-rails.html
# ELASTIC_APM_SERVER_URL=
# ELASTIC_APM_SECRET_TOKEN=

## Sentry
# SENTRY_DSN=

## LogRocket
# LOG_ROCKET_PROJECT_ID=xxxxx/some-project

## Scout
## https://scoutapm.com/docs/ruby/configuration
# SCOUT_KEY=YOURKEY
# SCOUT_NAME=YOURAPPNAME (Production)
# SCOUT_MONITOR=true

## NewRelic
# https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration/
# NEW_RELIC_LICENSE_KEY=
# Set this to true to allow newrelic apm to send logs.
# This is turned off by default.
# NEW_RELIC_APPLICATION_LOGGING_ENABLED=

## Datadog
## https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#environment-variables
# DD_TRACE_AGENT_URL=

# MaxMindDB API key to download GeoLite2 City database
# IP_LOOKUP_API_KEY=

## Rack Attack configuration
## To prevent and throttle abusive requests
# ENABLE_RACK_ATTACK=true

## Running chatwoot as an API only server
## setting this value to true will disable the frontend dashboard endpoints
# CW_API_ONLY_SERVER=false

## Development Only Config
# if you want to use letter_opener for local emails
# LETTER_OPENER=true
# meant to be used in github codespaces
# WEBPACKER_DEV_SERVER_PUBLIC=

# If you want to use official mobile app,
# the notifications would be relayed via a chatwoot server
ENABLE_PUSH_RELAY_SERVER=true

# Stripe API key
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=

# Set to true if you want to upload files to cloud storage using the signed url
# Make sure to follow https://edgeguides.rubyonrails.org/active_storage_overview.html#cross-origin-resource-sharing-cors-configuration on the cloud storage after setting this to true.
DIRECT_UPLOADS_ENABLED=

#MS OAUTH creds
AZURE_APP_ID=
AZURE_APP_SECRET=

## Advanced configurations
## Change these values to fine tune performance
# control the concurrency setting of sidekiq
# SIDEKIQ_CONCURRENCY=10

INSTALLATION_ENV=linux_script

**Comment by sojan-official** [comment]
Hey Everyone 

ref: https://github.com/chatwoot/chatwoot/blob/b94c89ebf1be7ae4a97700dc591915d958d060f8/config/initializers/mailer.rb#L32

Chatwoot tries to revert back to `sendmail` if there is no smtp address available in your environment files. Could you check in the rails console the value for `ENV['SMTP_ADDRESS']`


@mredodos @ssh-sato @mthakur5

**Comment by juliomac** [comment]
Same Here. Checked ENV['SMTP_ADDRESS'] and got it NOT empty.

{:address=>"email.com",
 :port=>"465",
 :authentication=>:login,
 :domain=>"email.com",
 :user_name=>"user@email.com",
 :password=>"password",
 :enable_starttls_auto=>true,
 :openssl_verify_mode=>"peer",
 :open_timeout=>5,
 :read_timeout=>5} 

Testing on Rails console but no clear Error messages. Only shows it timed out.

**Comment by mredodos** [comment]
> ENV['SMTP_ADDRESS']

at my end yes in rails console appear all the env variables and smtp_address is there.

and via rails test all works

**Comment by ssh-sato** [comment]
@sojan-official 
from rails console:
ActionMailer::Base.smtp_settings
i got this : {:address=>"localhost", :port=>25, :domain=>"localhost.localdomain", :user_name=>nil, :password=>nil, :authentication=>nil, :enable_starttls_auto=>true, :open_timeout=>5, :read_timeout=>5}
it seems it's ignoring my smtp config in .Env file

**Comment by mredodos** [comment]
@sojan-official we need a solution i cant send  no one email. i had make a server with postal and incoming and out works but chatwoot have that issue

**Comment by juliomac** [comment]
How to set variable open_timeout and read_timeout in .env?  It seems that setting them higher maybe the key to get mails out.

**Comment by omertahaoztop** [comment]
Same.. pls help

**Comment by omertahaoztop** [comment]
> @sojan-official we need a solution i cant send  no one email. i had make a server with postal and incoming and out works but chatwoot have that issue 

Have you been solve this?

**Comment by juliomac** [comment]
I have "solved" using Gmail. It seems ChatWoot does not wait too long for other SMTP servers

**Comment by carleii** [comment]
thanks for the feed back

**Comment by sojan-official** [comment]
- Tested out .env config and there doesn't seem to be a specific issue with code per say. The issues could be provider / config issue. Lets reopen this if this still persists on latest Chatwoot releases.

**Comment by ssh-sato** [comment]
i got it working, my dirty fix was to duplicate config.action_mailer.smtp_settings to production.rb

**Comment by juliomac** [comment]
> i got it working, my dirty fix was to duplicate config.action_mailer.smtp_settings to production.rb 

How do you do that? Is there a file "production.rb" you can edit?

**Comment by sojan-official** [comment]
@ssh-sato  @juliomac  you can just configure the environment variable `SMTP_PORT` in your .env file and do a restart

**Comment by ssh-sato** [comment]
@juliomac, @sojan-official  sry i'm not talking about the timeout, it's about Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:25
chatwoot v3 was not loading properly my smtp from .env , unlike the v2,
i forced it's loading by coping config.action_mailer.smtp_settings from config/initializers/mailer.rb to config/environments/production.rb

@juliomac, if you want to increase timeout, you need to add open_timeout and read_timeout in mailer.rb:
:open_timeout - Number of seconds to wait while attempting to open a connection.
:read_timeout - Number of seconds to wait until timing-out a read(2) call.
ref: https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
