### ISSUE TITLE
Slack integration has expired often

### ISSUE THREAD

**Issue by Chanli520** [chatwoot/chatwoot#7908]
### Describe the bug

why the  Slack integration has expired. To continue receiving messages on Slack, please delete the integration and connect your workspace again. ?

### To Reproduce

why the  Slack integration has expired. To continue receiving messages on Slack, please delete the integration and connect your workspace again. ?

### Expected behavior

why the  Slack integration has expired. To continue receiving messages on Slack, please delete the integration and connect your workspace again. ?

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

windows

### Browser and version

chrome

### Docker (if applicable)

why the  Slack integration has expired. To continue receiving messages on Slack, please delete the integration and connect your workspace again. ?

### Additional context

why the  Slack integration has expired. To continue receiving messages on Slack, please delete the integration and connect your workspace again. ?

**Comment by muhsin-k** [comment]
@Chanli520 There have been some recent [updates](https://github.com/chatwoot/chatwoot/pull/7852) to Slack permissions. If you want to send attachments through Slack using the Chatwoot integration, note that the integration may be disabled due to revised permissions required by Slack. Therefore, you will need to reconnect the Slack app with Chatwoot and update the permissions. This will re-enable the attachment feature and ensure seamless communication between you and your customers. Please let us know, if that is not the case.

**Comment by muhsin-k** [comment]
Closing this issue, for now. Please feel free to reopen this if it is still an issue.
