### ISSUE TITLE
Fix "SelectorFormat" issue in app/javascript/src/assets/scss/views/_signup.scss

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#80]
Selector `hero__title` should be written in lowercase with hyphens

https://codeclimate.com/github/chatwoot/chatwoot/app/javascript/src/assets/scss/views/_signup.scss#issue_5d87481187cf1900010005ca

**Comment by Jeff-Duke** [comment]
@pranavrajs I've opened #127 for this. The PR updates all the double-underscore selectors to double-hyphen to make them consistent with the rest of the app.

**Comment by kirillarutyunov** [comment]
@Jeff-Duke This need to discuss, because BEM naming use double-underscore for elements of block. Check here: http://getbem.com/naming/. 

Double-hyphen used for modifiers.

We need more information from @pranavrajs about naming in CSS in this project. There are 2 ways:
1. Not to use BEM,
2. Configure codeclimate checker for double-undescore selectors.

**Comment by pranavrajs** [comment]
@kirillarutyunov I agree that we want to follow BEM, I will try to read the docs on codeclimate configuration and change it to our requirements.
