### ISSUE TITLE
Interactive message (choice) does not trigger message_created event when using a webhook of an bot agent

### ISSUE THREAD

**Issue by aturyng** [chatwoot/chatwoot#8242]
### Describe the bug

I am building an integration of Chatwoot for Botpress.

I found a similar issue: https://github.com/chatwoot/chatwoot/issues/6745

### To Reproduce

1. User gets correctly displayed options to choose from in the web widget
2. User clicks on an option
3. No message is sent back using the message_created event

However, if user enters the option manually and sends it, then everything works currectly.

### Environment

Kubernetes

### Cloud Provider

AWS

### Platform

Browser

**Comment by aturyng** [comment]
Ok, so I figured out that so some reason I get a message of even type "message_updated". The body contains among other attributes the following:
```
...
 content_attributes: {
    items: [ [Object], [Object], [Object], [Object], [Object] ],
    submitted_values: [ [Object] ]
  },
...
```
Then I must read the submitted_values attribute to retrieve the submitted value.
Another strange thing is that the message sender is still the bot, even though the value was submitted by the user obviously.
```
...
sender: { id: 1, name: 'BotPressTestBot', type: 'agent_bot' },
...
```

Can you change it to the following?
1. A new message is sent of event type "message_created"
2. The sender is the user
3. The content is the choices (even though only single choice is supported)
Thanks!

**Comment by pranavrajs** [comment]
@aturyng We don't create new messages when the user clicks on the interactive messages, it is just an update event on the previous message.

**Comment by Nanod10** [comment]
It's good to find someone who is experiencing the same thing as me... @aturyng I have the same problem.

I'm only having this problem in the WebChat Widget.
In WhatsApp it works correctly when you press the buttons. The message is obviously on behalf of the user in this case.

I don't understand why the message is "refreshed" instead of "create a new message". I imagine that in other cases (like WhatsApp) new messages are created.

Should the message be sent on behalf of the bot?... 
Is there any specific reason for this to happen? 

From my point of view, in a conversation, there is at least one receiver, one sender and several messages sent by each one.
To give an example, in a conversation, if someone asks me a question, and I answer, the answer is from me, not from them.

It's a shame that we can't configure what type of response we want to use in the case of the buttons... Maybe by creating a new message on behalf of the user (instead of the bot) after click the button there would be a compatible bot between the different channels... 

But if not, what should we do? cancel buttons and send the typical text?
1 - blah blah
2- ble ble
3- bli bli" ??

I've been trying to solve this problem for 6 hours,
From my side it is not the expected operation (I know I'm nobody here but hey... let's be predisposed)
¿Maybe some idea or alternative solution to this so I can continue using buttons?

I have noticed that the response message is rendered inside the element with the class: 
.agent-message-wrap.has-response > .user-message-wrap

![image](https://github.com/chatwoot/chatwoot/assets/4501572/46596a29-eb6a-488d-8377-79c348db42a2)

@pranavrajs 
And when we send a manually written message, the main wrapper is .user-message-wrap directly, is that correct? or an error?

**Comment by Nanod10** [comment]
@pranavrajs  in issue #6745 they request logs from sidequik since they could not reproduce the problem

I am not able to place the logs in that issue because I am not a contributor, I have recently learned about the chatwoot platform and I am still getting familiar with several things (even ruby, rails, sidequick, everything is new to me)

The system is tremendously good! and I have been dancing between obstacles and solutions for 2 months heh... (but I have managed to run it completely in docker, connect FB, Insta, and WhatsApp, connect the bridge to use Botpress) and recently I have encountered this problem.

I attach the logs so you can review (if you would be so kind)
The intention is merely to collaborate and try to find a solution that allows me to continue advancing in the development of the bot using buttons.

[chatwoot.log](https://github.com/chatwoot/chatwoot/files/13531079/chatwoot.log)

[chatwoot-botpress-bridge.log](https://github.com/chatwoot/chatwoot/files/13531080/chatwoot-botpress-bridge.log)

[sidequik.log](https://github.com/chatwoot/chatwoot/files/13531081/sidequik.log)

Thank you!
