### ISSUE TITLE
Private notes displayed in the conversation email that is sent to customer

### ISSUE THREAD

**Issue by RonWalker22** [chatwoot/chatwoot#837]
**Describe the bug**

Private notes are displayed in the conversation email that the customer signs up for when they being a new chat.  

**To Reproduce**
1. Start a new chat as a customer. Sign up for the conversation to be emailed to you.
2. Add a private note and a few messages in the chat as an agent. 

**Expected behavior**
Private notes should not be included in the email that is sent to the customer.

**Comment by RonWalker22** [comment]
Looking at the schema, private messages are just messages with `private` attribute set to `true`. So they are the same model. 

The issue with this is that every time you pass the messages around you have to remember to filter out the private ones.  

Here's another idea. It might be better to have `private_message` as a separate model(different table). So when you interact with the `message` model you don't have to worry about the private message slipping in. Although this may not be dry, it's much safer.

**Comment by pranavrajs** [comment]
@RonWalker22 This seems to be a bug, we will have a fix for it soon.

**Comment by sojan-official** [comment]
@RonWalker22  thanks for bringing this up. we will add a default_scope to the messages table so that private messages are always filtered out. 
We can override the filter explicitly whenever fetching private messages are required. This will save us for now,  without doing much rework.

**Comment by sony-mathew** [comment]
Hey @RonWalker22, considering the severity of this issue, we took this on priority and have resolved this. We have created a dedicated release for this: https://github.com/chatwoot/chatwoot/releases/tag/v1.4.1

Thank you so much for bringing this to our attention and reporting the issue. On a side note, we appreciate your pointers on how to go about resolving this issue. For now, because of the severity, we have done a patch to solve the issue in the easiest way possible with the smallest set of possible changes. We have decided to come back and work on this area more in the upcoming releases to avoid such issues related to private notes.
