### ISSUE TITLE
Broken link in confirmation/password reset mails

### ISSUE THREAD

**Issue by Darth-Mader** [chatwoot/chatwoot#879]
I have deployed a chatwoot instance on a standalone VPS (not docker) through the git clone. 

After setting the SMTP service to work the links in the mails i get are pointing to localhost:3000 instead of the public IP of my machine.

For example the link in a password reset mail will point to 
`http://localhost:3000/app/auth/password/edit?reset_password_token=RwnzR_P6ybHpkrdq7QLx`
instead of the wanted
`http://PUBLIC_IP:3000/app/auth/password/edit?reset_password_token=RwnzR_P6ybHpkrdq7QLx`

In the environmental variables file I have set
`FRONTEND_URL=http://PUBLIC_IP:3000`

How can this be fixed?

**Comment by sojan-official** [comment]
@Darth-Mader  did you restart the server after setting the value in .env file ?

**Comment by sojan-official** [comment]
@Darth-Mader  also ensure that the 'RAILS_ENV' value is set to production in .env file

**Comment by Darth-Mader** [comment]
> @Darth-Mader also ensure that the 'RAILS_ENV' value is set to production in .env file
Now after changing the value to production the server won't start as I'm immediately getting this error:
`frontend.1 | webpack dev_server configuration not found in /home/rchatwok42/domains/chatwoot.test/public_html/chatwoot/config/webpacker.yml[production]`

How can I safely move into production?

**Comment by sojan-official** [comment]
@Darth-Mader  I think the set up that you followed was the one meant for development purposes. You don't need to run webpack dev server in production. 

currently, I guess you would be starting the server using something like `foreman start Procfile.dev` instead of .dev Procfile . just use the  `forman start -f Procfile` 

for production set up, you can also use something like caprover which makes the whole process much easier : https://isotropic.co/how-to-install-chatwoot-to-a-digitalocean-droplet/

**Comment by sojan-official** [comment]
@Darth-Mader  closing this out for now. let us know if you face any issues 
also the fix in : https://github.com/chatwoot/chatwoot/commit/f6a9f791cfa87411ce184ee14ed97c05d25a152e should take front end URL even in development environments.
