### ISSUE TITLE
Tag bug

### ISSUE THREAD

**Issue by muriloorama** [chatwoot/chatwoot#9094]
### Describe the bug

When you add more than 14 tags, the contact freezes, you can't even add or remove the tags. the only way is to delete the contact and add less than 14 tags

### To Reproduce

When you add more than 14 tags, the contact freezes, you can't even add or remove the tags. the only way is to delete the contact and add less than 14 tags

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Browser and version

3.6.0

### Additional context

When you add more than 14 tags, the contact freezes, you can't even add or remove the tags. the only way is to delete the contact and add less than 14 tags

**Comment by pranavrajs** [comment]
@muriloorama Interesting! Let us test it out

**Comment by scmmishra** [comment]
@muriloorama we couldn't verify this exactly, which OS and browser are you using?

**Comment by muriloorama** [comment]
I'm using Windows 11 and Chrome. Did you manage to add more than 14 tags and then remove them?

**Comment by pranavrajs** [comment]
@sojan @shivam One potential issue could be that the cached_label_list is a string, limited to 255 characters, compared to the text field's 30,000 characters. The bug might occur if the field overflows due to an abundance of labels.

The number 14 may not be significant, but the total number of characters in the labels could be. Try adding more labels to see if the issue persists.

We are testing with labels of 5-10 characters each. The total combined character count should be around 140, which is still within the acceptable limits. Try adding more to see if you can reproduce it.

**Comment by scmmishra** [comment]
Let me give this a shot

**Comment by scmmishra** [comment]
> Member

@pranavrajs you were right! I've fixed this in https://github.com/chatwoot/chatwoot/pull/9143
