### ISSUE TITLE
Delete old files to avoid disk overload - Maintainability

### ISSUE THREAD

**Issue by Gustaps** [chatwoot/chatwoot#9118]
### Is your feature or enhancement related to a problem? Please describe.

I have concerns in the context of Chatwoot's maintainability, in relation to the various files it stores, such as documents, PDFs, media files, etc. Where are these files located on the disk?
I entered the /storage directory but I didn't understand the nomenclature. 

### Describe the solution you'd like

As I haven't found any documentation regarding this, if it doesn't already exist, maybe provide a configuration that indicates the validity period of the files. After this deadline, shall be removed automatically. 
Regarding the tables in database, which ones can I access to delete old registers?

I'm using Chatwoot 3.1.1.

**Comment by sojan-official** [comment]
In production systems, its recommended to configure a cloud storage: https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers/ 

Since the messages are persisted in Chatwoot, we can't remove old files. 

Also, note we don't provide backward support for older versions. The recommendation is always to keep your version updated.
