### ISSUE TITLE
Typing a @ in Private Note switches to Reply tab (with German keyboard layout)

### ISSUE THREAD

**Issue by jochenstu** [chatwoot/chatwoot#9492]
### Describe the bug

Since 3.9 on a Mac, pressing option + l in "Private Note" will switch to the "Reply" tab, which is an issue because option + l is the shortcut for "@".

https://github.com/chatwoot/chatwoot/assets/1176036/dec628d6-cd9b-4f3c-b253-8f7caaa6f255

### To Reproduce

As far as I can tell, just press option + l in the "Private Note" tab

(German/qwertz keyboard layout/current MacOS/current Chrome)

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

MacOS

### Browser and version

Current Chrome

**Comment by jokiatgithub** [comment]
happens actually everywhere when you try to write an @ in the system.
happens only on macos
the keyboard shortcut "option + L" means switching to reply... but is as well the way how you write an @ with german keyboard layout.

**Comment by iamsivin** [comment]
@jochenstu We've now added a `Shift` modifier to the existing shortcuts `(Alt+KeyP, Alt+KeyL)` to avoid conflicts. For example, `Shift+Alt+KeyL`. Specifically, the shortcuts for toggling between the reply and private note editors now use `Shift+Alt+KeyP` and `Shift+Alt+KeyL` when the QWERTZ layout is active. Otherwise, they remain the same as before.
