### ISSUE TITLE
Feature: Email a copy of the chat transcript

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#964]
When a conversation is resolved, I might need the entire transcript for documenting purposes. There should be an option to send 

1. a mail to the user involved in the conversation
2. a mail to the agent handling the conversation
3. a mail to a email address which can be specified from the ui.

- Sidebar has email this conversation form (Irrespective of resolved/open status of the conversation)
- Resolve button will have Resolve and resolve + email option

**Comment by iammattmartin** [comment]
Might need to factor in here what happens when someone re-opens a convo? We'd not want the whole thing emailed again.

As conversations can't be closed (i.e new chat messages will constantly re-open), these cold get excessively long and so could that email.

**Comment by pranavrajs** [comment]
@iammattmartin Yeah, this is a conceptual rather than an implementation one. We are trying to do it as follows

1. **WebChannel**: At present, widget supports only a single view of conversations, we will be adding support for multiple conversations which would resolve this problem.

2. **Facebook/Twitter/Whatsapp/SMS**: There is no concept of multiple conversations here. Event if Chatwoot treats it as different conversation, the end-user see only a big list of messages on their end. 

The channels come with an additional challenge in resolving a conversation. Let us say the agent resolved a conversation. Then the user sends a gratitude message like Thanks or Bye or anything of that sort. (there is no separate thread concept in these channels ). This shouldn't create a new conversation. There are two ways to approach this problem.

1. Have a list of messages which can be ignored if the conversation is resolved. This is complex to build as there are multiple languages, multiple dialects, so making this approach perfect is a harder one.

2. Allow the admin to configure a buffer time for re-opening the conversation. Let us say the admin set the buffer time as 1 day. Any message sent in between that time would not create a new conversation, rather it would re-open the old one. 

The second approach seems cleaner and easier to work with. This is something we would get feedback on. We are definitely moving towards a path where an end-user can have multiple conversations rather than a big single thread. Once that's completed, there wouldn't issue with longer email threads.

**Comment by iammattmartin** [comment]
I think for FB, Twitter, Whatsapp, SMS - these would need to be treated differently.

Social/WA/SMS; a time out after X period. Other people like KLM and Barclays do this so if they've not heard from you for a while, a new conversation is started. A few days would be reasonably but having this user defined to their inbox is best.

For things like threaded Facebook posts and Twitter threads instead of appearing as one they create a new conversation for each thread ID, this isn't so much an issue (when/if supported).

For 2.1, possibly, or maybe an intermediate status. "Pending", instead of Resolved. Likewise, if goes to pending automatically on reply but then can change to Resolved after X days. After which logic could decide to re-open or start a new one. In any case, you can see a persons conversations so it's not hard to find.

Maybe at the top of the new conversation window you could have "you last spoke to this person on X date, click here to load that conversation" which will just back-fill on screen. Maybe even an option to merge conversations if the same thing.

2.2 is good and does follow the above to e degree but allowing the user to control how this works would be best instead of everyone having to use it a certain way.

More on the website chat though, the visitor should be able to end the chat as well as the staff member. This avoids simple messages like "thanks".

I guess there needs to be some clarification on the website chat though as in some places it is called chat but in reality, it may not be real time, so it is more a messenger. Could be scope to have this to only work when people are online and thus real time online and therefore one coversation per visit, although still allowing those who want to use a persistent messenger etc.
