### ISSUE TITLE
发送给客户图片后，客户端收到的图片前端错误信息

### ISSUE THREAD

**Issue by phpmac** [chatwoot/chatwoot#9671]
### Describe the bug

https://https/rails/acti

这是发送给客户图片后，客户端收到的图片前端错误信息

### To Reproduce

https://https/rails/acti

这是发送给客户图片后，客户端收到的图片前端错误信息

### Environment

Docker

### Cloud Provider

None

### Platform

None

**Comment by vishnu-narayanan** [comment]
@phpmac, please add more details about the issue. Include error logs.

From the limited context, it appears that the issue might be due to an active storage service. Have you set up an active storage service with your installation? We recommend something like AWS s3. 

https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers

**Comment by pranavrajs** [comment]
@phpmac I would suggest using English if possible in the discussion as it would easier for everyone to follow.

**Comment by pranavrajs** [comment]
Closing this here for now due to inactivity.
