### ISSUE TITLE
ActiveStorage::FileNotFoundError When sending an image via Api

### ISSUE THREAD

**Issue by TheOneironaut** [chatwoot/chatwoot#9675]
### Describe the bug

I use docker compose with the latest version.
When I send or receive a picture, it is not sent and the Sidekiq logs shows the error - ActiveStorage::FileNotFoundError.

My storage: ACTIVE_STORAGE_SERVICE=local

I installed chatwoot on my linux server using coolify on hetzner cloud.

I send and receive the messages using evolution api (WhatsApp).

### To Reproduce

Installation via docker compose

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

ubuntu

### Docker (if applicable)

yes

![image](https://github.com/chatwoot/chatwoot/assets/43513454/6df1e1e2-acc8-4068-8810-e62fdbae151b)

**Comment by thiagodebugs** [comment]
+1 on WhatsApp Cloud API

**Comment by vishnu-narayanan** [comment]
@TheOneironaut Have you configured an active storage service? It is recommended that you set up something like an S3 or any S3 API-compatible storage service.

https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers

**Comment by TheOneironaut** [comment]
> @TheOneironaut Have you configured an active storage service? It is recommended that you set up something like an S3 or any S3 API-compatible storage service.
> 
> https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers

I don't want external storage.
my setup is:
ACTIVE_STORAGE SERVICE=local

Send a message in "ActiveStorage::FileNotFoundError"

Is there a problem with this?

**Comment by pranavrajs** [comment]
@TheOneironaut The issue here is not with Chatwoot. It seems that you might not have a persistent storage setup configured. The docker-compose we have is just for getting started, you need to configure it properly for production usage based on your requirements.

In this case, you need to specify the storage folder as a volume and make sure that the folder is getting stored persistently. https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose

Closing this here for now.
