### ISSUE TITLE
Compilation failed on a fresh install on Amazon EC2 Ubuntu 20

### ISSUE THREAD

**Issue by killion** [chatwoot/chatwoot#9676]
### Describe the bug

Running `sudo cwctl -i` in a clean directory on an Amazon EC2 instance the log ends with `Compilation failed:` and no further errors.
[cwctl -i.log](https://github.com/user-attachments/files/15962632/cwctl.-i.log)

### To Reproduce

1. On a new Amazon EC2 instance run `sudo cwctl -i`

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211129

### Additional context

c5.large EC2 Instance

**Comment by killion** [comment]
This seems to be a Webpacker memory problem. I switched to an instance type with 8GB of RAM and it completes. It had been running on a 4GB instance for year. Closing...

**Comment by vishnu-narayanan** [comment]
@killion If you are pressed for memory, docker based deployment would be a better choice.

**Comment by killion** [comment]
Thanks @vishnu-narayanan! Is the Docker version the generally recommended way to go as well?

**Comment by pranavrajs** [comment]
@killion The most of the resources required is for compilation which is why Docker works well. You could run it on a 2GB or even lesser machine without any issues. However, for the regular installation, it needs 4GB + a good swap space. Since we don't have the tooling like cwctl on docker, we have not started recommending it completely. 

One thing you can do to improve the situation without switching to docker installation is to add swap space of 8GB or more if you don't have it already. This should work in most cases.
