### ISSUE TITLE
Feature: Support for DigitalOcean Spaces

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#968]
- Add support for digital ocean spaces

**Comment by lucasilverentand** [comment]
The solution is fairly simple you basically need to support changing the endpoint to which you make calls, this should be one variable in the config. At the moment I'm not familiar with the source code of chatwoot so it would take me some time to dig in. Maybe someone else that has more knowledge of the codebase could add this within half an hour. Otherwise, I'd be glad to have a look into it.

**Comment by petebytes** [comment]
@lucasilverentand I made what I think are the necessary changes, would you be able to test the draft PR I have opened?

PR https://github.com/chatwoot/chatwoot/pull/1011
