### ISSUE TITLE
Tweets from other users in conversation

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#982]
**Describe the bug**
When someone tweets you and others, whilst our replies will appear in the same thread, if someone else also replies in that thread, it appears in the conversation in CW as from the person who originally tweeted us (and started the conversation).

**To Reproduce**
Steps to reproduce the behaviour:
Tweet in to CW from one user.
Another user should then tweet in to that thread.
Both appear in the same conversation in CW.

**Expected behaviour**
Either tweets from anyone but the original person should not appear in the conversation in CW, or for "third party" messages, they should be noted as such including who they were from (@username) maybe a link and the ability to reply to them directly.

**Screenshots**
Two screen shots showing thread. Numbered although tweets are in reverse order but you can still marry up the numbers. 5 on both is the third party (not original poster, or us replying).

<img width="383" alt="Screenshot 2020-06-26 at 4 15 15 AM" src="https://user-images.githubusercontent.com/15971590/85816863-580bc380-b764-11ea-9a28-5877af8328b2.png">
<img width="842" alt="Screenshot 2020-06-26 at 4 13 03 AM" src="https://user-images.githubusercontent.com/15971590/85816872-5cd07780-b764-11ea-8171-93efde843e34.png">

**Comment by pranavrajs** [comment]
@iammattmartin 

The contact shown at the top is the person who has created the parent tweet, rest of them are the replies to that particular tweet. If you hover the message, it should be showing the user who has sent that tweet. The concept of conversation participants was recently added and was not available before. This is the reason for this UX difficulty. 

To be honest, in the current UI, it is confusing to know who sent what, we had a ticket to improve the UX for tweet layouts, this got deprioritized due to some other reasons. (https://github.com/chatwoot/chatwoot/issues/818). 

### How are we going to improve it

#### 1. The concept of conversation participants. 

Right now the UI shows the owner of the conversation, it does not show who all have participated in that conversation. Instead of showing a single contact, we can show a group of people who have participated in the conversation, like the one below. 

<img width="142" alt="Screenshot 2020-06-26 at 1 13 38 PM" src="https://user-images.githubusercontent.com/2246121/85833124-dc833400-b7ae-11ea-9466-256377f9944f.png">

#### 2. Improve the message interface to show the user details without hovering.

Right now, the contact details are shown on hover of each message, change this to a thumbnail right next to the message. (A similar UX is shown below)

#### 3. Reply to any tweet by clicking on it. 

On each tweet, we will add action to reply which would enable you to reply to any tweet in the thread. 

<img width="354" alt="Screenshot 2020-06-26 at 1 17 43 PM" src="https://user-images.githubusercontent.com/2246121/85833492-6cc17900-b7af-11ea-80ff-f35b7ef53967.png">

I think this should resolve the confusion happening right now. I think the way the conversation is handled right now is correct, because a tweet thread should be one single conversation, otherwise there will be a loss of context. The problem is the way it is represented which will be resolved as show above.

**Comment by iammattmartin** [comment]
Sounds good. Right now a hover does not work on messages as far as I can see? Looking in the code too there is nothing on the specific `<li>`, or within the generate that.

We're using this more for Twitter now and this has happened twice in the last two days so is quite confusing.

**Comment by iammattmartin** [comment]
Another consideration here is how data from third users is stored (i.e those replying to mid-thread tweets).

Currently they still all appear in the original tweet authors thread.

It would be pertinent to be able to split out a single authors message so when you reply to them and they reply to you, it is consider its own thread.
